// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.1
// 	protoc        v3.21.12
// source: artifacts.proto

package artifactspb

import (
	chunkpb "github.com/DataExMachina-dev/side-eye-go/internal/chunkpb"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetArtifactRequest_Kind int32

const (
	GetArtifactRequest_UNKNOWN          GetArtifactRequest_Kind = 0
	GetArtifactRequest_BPF              GetArtifactRequest_Kind = 1
	GetArtifactRequest_METADATA         GetArtifactRequest_Kind = 2
	GetArtifactRequest_BPF_SOURCE       GetArtifactRequest_Kind = 3
	GetArtifactRequest_SPEC             GetArtifactRequest_Kind = 5
	GetArtifactRequest_SNAPSHOT_PROGRAM GetArtifactRequest_Kind = 6
)

// Enum value maps for GetArtifactRequest_Kind.
var (
	GetArtifactRequest_Kind_name = map[int32]string{
		0: "UNKNOWN",
		1: "BPF",
		2: "METADATA",
		3: "BPF_SOURCE",
		5: "SPEC",
		6: "SNAPSHOT_PROGRAM",
	}
	GetArtifactRequest_Kind_value = map[string]int32{
		"UNKNOWN":          0,
		"BPF":              1,
		"METADATA":         2,
		"BPF_SOURCE":       3,
		"SPEC":             5,
		"SNAPSHOT_PROGRAM": 6,
	}
)

func (x GetArtifactRequest_Kind) Enum() *GetArtifactRequest_Kind {
	p := new(GetArtifactRequest_Kind)
	*p = x
	return p
}

func (x GetArtifactRequest_Kind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GetArtifactRequest_Kind) Descriptor() protoreflect.EnumDescriptor {
	return file_artifacts_proto_enumTypes[0].Descriptor()
}

func (GetArtifactRequest_Kind) Type() protoreflect.EnumType {
	return &file_artifacts_proto_enumTypes[0]
}

func (x GetArtifactRequest_Kind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GetArtifactRequest_Kind.Descriptor instead.
func (GetArtifactRequest_Kind) EnumDescriptor() ([]byte, []int) {
	return file_artifacts_proto_rawDescGZIP(), []int{0, 0}
}

type GetArtifactRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The key associated with this artifact.
	Key string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	// The kind of artifact to retrieve.
	Kind GetArtifactRequest_Kind `protobuf:"varint,2,opt,name=kind,proto3,enum=artifacts.GetArtifactRequest_Kind" json:"kind,omitempty"`
}

func (x *GetArtifactRequest) Reset() {
	*x = GetArtifactRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_artifacts_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetArtifactRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetArtifactRequest) ProtoMessage() {}

func (x *GetArtifactRequest) ProtoReflect() protoreflect.Message {
	mi := &file_artifacts_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetArtifactRequest.ProtoReflect.Descriptor instead.
func (*GetArtifactRequest) Descriptor() ([]byte, []int) {
	return file_artifacts_proto_rawDescGZIP(), []int{0}
}

func (x *GetArtifactRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *GetArtifactRequest) GetKind() GetArtifactRequest_Kind {
	if x != nil {
		return x.Kind
	}
	return GetArtifactRequest_UNKNOWN
}

var File_artifacts_proto protoreflect.FileDescriptor

var file_artifacts_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x61, 0x72, 0x74, 0x69, 0x66, 0x61, 0x63, 0x74, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x09, 0x61, 0x72, 0x74, 0x69, 0x66, 0x61, 0x63, 0x74, 0x73, 0x1a, 0x0b, 0x63, 0x68,
	0x75, 0x6e, 0x6b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xc0, 0x01, 0x0a, 0x12, 0x47, 0x65,
	0x74, 0x41, 0x72, 0x74, 0x69, 0x66, 0x61, 0x63, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b,
	0x65, 0x79, 0x12, 0x36, 0x0a, 0x04, 0x6b, 0x69, 0x6e, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e,
	0x32, 0x22, 0x2e, 0x61, 0x72, 0x74, 0x69, 0x66, 0x61, 0x63, 0x74, 0x73, 0x2e, 0x47, 0x65, 0x74,
	0x41, 0x72, 0x74, 0x69, 0x66, 0x61, 0x63, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e,
	0x4b, 0x69, 0x6e, 0x64, 0x52, 0x04, 0x6b, 0x69, 0x6e, 0x64, 0x22, 0x60, 0x0a, 0x04, 0x4b, 0x69,
	0x6e, 0x64, 0x12, 0x0b, 0x0a, 0x07, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x10, 0x00, 0x12,
	0x07, 0x0a, 0x03, 0x42, 0x50, 0x46, 0x10, 0x01, 0x12, 0x0c, 0x0a, 0x08, 0x4d, 0x45, 0x54, 0x41,
	0x44, 0x41, 0x54, 0x41, 0x10, 0x02, 0x12, 0x0e, 0x0a, 0x0a, 0x42, 0x50, 0x46, 0x5f, 0x53, 0x4f,
	0x55, 0x52, 0x43, 0x45, 0x10, 0x03, 0x12, 0x08, 0x0a, 0x04, 0x53, 0x50, 0x45, 0x43, 0x10, 0x05,
	0x12, 0x14, 0x0a, 0x10, 0x53, 0x4e, 0x41, 0x50, 0x53, 0x48, 0x4f, 0x54, 0x5f, 0x50, 0x52, 0x4f,
	0x47, 0x52, 0x41, 0x4d, 0x10, 0x06, 0x22, 0x04, 0x08, 0x04, 0x10, 0x04, 0x32, 0x4f, 0x0a, 0x0d,
	0x41, 0x72, 0x74, 0x69, 0x66, 0x61, 0x63, 0x74, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x12, 0x3e, 0x0a,
	0x0b, 0x47, 0x65, 0x74, 0x41, 0x72, 0x74, 0x69, 0x66, 0x61, 0x63, 0x74, 0x12, 0x1d, 0x2e, 0x61,
	0x72, 0x74, 0x69, 0x66, 0x61, 0x63, 0x74, 0x73, 0x2e, 0x47, 0x65, 0x74, 0x41, 0x72, 0x74, 0x69,
	0x66, 0x61, 0x63, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x0c, 0x2e, 0x63, 0x68,
	0x75, 0x6e, 0x6b, 0x2e, 0x43, 0x68, 0x75, 0x6e, 0x6b, 0x22, 0x00, 0x30, 0x01, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_artifacts_proto_rawDescOnce sync.Once
	file_artifacts_proto_rawDescData = file_artifacts_proto_rawDesc
)

func file_artifacts_proto_rawDescGZIP() []byte {
	file_artifacts_proto_rawDescOnce.Do(func() {
		file_artifacts_proto_rawDescData = protoimpl.X.CompressGZIP(file_artifacts_proto_rawDescData)
	})
	return file_artifacts_proto_rawDescData
}

var file_artifacts_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_artifacts_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_artifacts_proto_goTypes = []interface{}{
	(GetArtifactRequest_Kind)(0), // 0: artifacts.GetArtifactRequest.Kind
	(*GetArtifactRequest)(nil),   // 1: artifacts.GetArtifactRequest
	(*chunkpb.Chunk)(nil),        // 2: chunk.Chunk
}
var file_artifacts_proto_depIdxs = []int32{
	0, // 0: artifacts.GetArtifactRequest.kind:type_name -> artifacts.GetArtifactRequest.Kind
	1, // 1: artifacts.ArtifactStore.GetArtifact:input_type -> artifacts.GetArtifactRequest
	2, // 2: artifacts.ArtifactStore.GetArtifact:output_type -> chunk.Chunk
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_artifacts_proto_init() }
func file_artifacts_proto_init() {
	if File_artifacts_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_artifacts_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetArtifactRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_artifacts_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_artifacts_proto_goTypes,
		DependencyIndexes: file_artifacts_proto_depIdxs,
		EnumInfos:         file_artifacts_proto_enumTypes,
		MessageInfos:      file_artifacts_proto_msgTypes,
	}.Build()
	File_artifacts_proto = out.File
	file_artifacts_proto_rawDesc = nil
	file_artifacts_proto_goTypes = nil
	file_artifacts_proto_depIdxs = nil
}
