// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.1
// 	protoc        v3.21.12
// source: machina.proto

package machinapb

import (
	chunkpb "github.com/DataExMachina-dev/side-eye-go/internal/chunkpb"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WatchProcessesRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Predicates which are used to filter the processes. The resulting set will
	// be the disjunction of the predicates (OR).
	LabelRules []*LabelRule `protobuf:"bytes,2,rep,name=label_rules,json=labelRules,proto3" json:"label_rules,omitempty"`
}

func (x *WatchProcessesRequest) Reset() {
	*x = WatchProcessesRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_machina_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WatchProcessesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchProcessesRequest) ProtoMessage() {}

func (x *WatchProcessesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_machina_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchProcessesRequest.ProtoReflect.Descriptor instead.
func (*WatchProcessesRequest) Descriptor() ([]byte, []int) {
	return file_machina_proto_rawDescGZIP(), []int{0}
}

func (x *WatchProcessesRequest) GetLabelRules() []*LabelRule {
	if x != nil {
		return x.LabelRules
	}
	return nil
}

type Update struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The process which was updated.
	Added   []*Process `protobuf:"bytes,1,rep,name=added,proto3" json:"added,omitempty"`
	Removed []string   `protobuf:"bytes,2,rep,name=removed,proto3" json:"removed,omitempty"`
}

func (x *Update) Reset() {
	*x = Update{}
	if protoimpl.UnsafeEnabled {
		mi := &file_machina_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Update) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Update) ProtoMessage() {}

func (x *Update) ProtoReflect() protoreflect.Message {
	mi := &file_machina_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Update.ProtoReflect.Descriptor instead.
func (*Update) Descriptor() ([]byte, []int) {
	return file_machina_proto_rawDescGZIP(), []int{1}
}

func (x *Update) GetAdded() []*Process {
	if x != nil {
		return x.Added
	}
	return nil
}

func (x *Update) GetRemoved() []string {
	if x != nil {
		return x.Removed
	}
	return nil
}

type GetExecutableRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The path to the executable.
	Hash string `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
}

func (x *GetExecutableRequest) Reset() {
	*x = GetExecutableRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_machina_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetExecutableRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetExecutableRequest) ProtoMessage() {}

func (x *GetExecutableRequest) ProtoReflect() protoreflect.Message {
	mi := &file_machina_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetExecutableRequest.ProtoReflect.Descriptor instead.
func (*GetExecutableRequest) Descriptor() ([]byte, []int) {
	return file_machina_proto_rawDescGZIP(), []int{2}
}

func (x *GetExecutableRequest) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

// The SnapshotRequest drives the snapshot process.
type SnapshotRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Request:
	//
	//	*SnapshotRequest_Setup_
	//	*SnapshotRequest_Snapshot_
	Request isSnapshotRequest_Request `protobuf_oneof:"request"`
}

func (x *SnapshotRequest) Reset() {
	*x = SnapshotRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_machina_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SnapshotRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SnapshotRequest) ProtoMessage() {}

func (x *SnapshotRequest) ProtoReflect() protoreflect.Message {
	mi := &file_machina_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SnapshotRequest.ProtoReflect.Descriptor instead.
func (*SnapshotRequest) Descriptor() ([]byte, []int) {
	return file_machina_proto_rawDescGZIP(), []int{3}
}

func (m *SnapshotRequest) GetRequest() isSnapshotRequest_Request {
	if m != nil {
		return m.Request
	}
	return nil
}

func (x *SnapshotRequest) GetSetup() *SnapshotRequest_Setup {
	if x, ok := x.GetRequest().(*SnapshotRequest_Setup_); ok {
		return x.Setup
	}
	return nil
}

func (x *SnapshotRequest) GetSnapshot() *SnapshotRequest_Snapshot {
	if x, ok := x.GetRequest().(*SnapshotRequest_Snapshot_); ok {
		return x.Snapshot
	}
	return nil
}

type isSnapshotRequest_Request interface {
	isSnapshotRequest_Request()
}

type SnapshotRequest_Setup_ struct {
	Setup *SnapshotRequest_Setup `protobuf:"bytes,1,opt,name=setup,proto3,oneof"`
}

type SnapshotRequest_Snapshot_ struct {
	Snapshot *SnapshotRequest_Snapshot `protobuf:"bytes,2,opt,name=snapshot,proto3,oneof"`
}

func (*SnapshotRequest_Setup_) isSnapshotRequest_Request() {}

func (*SnapshotRequest_Snapshot_) isSnapshotRequest_Request() {}

type SnapshotResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data []byte `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	// The timestamp of the snapshot. This is a best-effort timestamp that
	// should closely match the time at which the snapshot was taken.
	Timestamp *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// The duration of the pause for the snapshot as observed by the agent.
	PauseDurationNs uint64 `protobuf:"varint,3,opt,name=pause_duration_ns,json=pauseDurationNs,proto3" json:"pause_duration_ns,omitempty"`
}

func (x *SnapshotResponse) Reset() {
	*x = SnapshotResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_machina_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SnapshotResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SnapshotResponse) ProtoMessage() {}

func (x *SnapshotResponse) ProtoReflect() protoreflect.Message {
	mi := &file_machina_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SnapshotResponse.ProtoReflect.Descriptor instead.
func (*SnapshotResponse) Descriptor() ([]byte, []int) {
	return file_machina_proto_rawDescGZIP(), []int{4}
}

func (x *SnapshotResponse) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *SnapshotResponse) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *SnapshotResponse) GetPauseDurationNs() uint64 {
	if x != nil {
		return x.PauseDurationNs
	}
	return 0
}

type MachinaInfoRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *MachinaInfoRequest) Reset() {
	*x = MachinaInfoRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_machina_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MachinaInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MachinaInfoRequest) ProtoMessage() {}

func (x *MachinaInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_machina_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MachinaInfoRequest.ProtoReflect.Descriptor instead.
func (*MachinaInfoRequest) Descriptor() ([]byte, []int) {
	return file_machina_proto_rawDescGZIP(), []int{5}
}

type MachinaInfoResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// A unique identifier for this machina.
	Fingerprint string `protobuf:"bytes,1,opt,name=fingerprint,proto3" json:"fingerprint,omitempty"`
	// The hostname of the machina.
	Hostname string `protobuf:"bytes,3,opt,name=hostname,proto3" json:"hostname,omitempty"`
	// The version of the machina.
	Version string `protobuf:"bytes,4,opt,name=version,proto3" json:"version,omitempty"`
	// The token of the tenant to which this machina belongs.
	//
	// TODO: Define any structure for this token. For now it's opaque and will
	// correspond to the token used to scope requests to a tenant.
	TenantToken string `protobuf:"bytes,5,opt,name=tenant_token,json=tenantToken,proto3" json:"tenant_token,omitempty"`
	// The environment flag passed to the machina.
	Environment string `protobuf:"bytes,6,opt,name=environment,proto3" json:"environment,omitempty"`
	// The IP addresses of the machina.
	IpAddresses []string `protobuf:"bytes,7,rep,name=ip_addresses,json=ipAddresses,proto3" json:"ip_addresses,omitempty"`
}

func (x *MachinaInfoResponse) Reset() {
	*x = MachinaInfoResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_machina_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MachinaInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MachinaInfoResponse) ProtoMessage() {}

func (x *MachinaInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_machina_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MachinaInfoResponse.ProtoReflect.Descriptor instead.
func (*MachinaInfoResponse) Descriptor() ([]byte, []int) {
	return file_machina_proto_rawDescGZIP(), []int{6}
}

func (x *MachinaInfoResponse) GetFingerprint() string {
	if x != nil {
		return x.Fingerprint
	}
	return ""
}

func (x *MachinaInfoResponse) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *MachinaInfoResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *MachinaInfoResponse) GetTenantToken() string {
	if x != nil {
		return x.TenantToken
	}
	return ""
}

func (x *MachinaInfoResponse) GetEnvironment() string {
	if x != nil {
		return x.Environment
	}
	return ""
}

func (x *MachinaInfoResponse) GetIpAddresses() []string {
	if x != nil {
		return x.IpAddresses
	}
	return nil
}

// Setup is the first message from the client in the Snapshot protocol.
type SnapshotRequest_Setup struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The key associated with the artifacts needed for this snapshot.
	Key string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	// The fingerprint of the process to snapshot.
	ProcessFingerprint string `protobuf:"bytes,2,opt,name=process_fingerprint,json=processFingerprint,proto3" json:"process_fingerprint,omitempty"`
}

func (x *SnapshotRequest_Setup) Reset() {
	*x = SnapshotRequest_Setup{}
	if protoimpl.UnsafeEnabled {
		mi := &file_machina_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SnapshotRequest_Setup) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SnapshotRequest_Setup) ProtoMessage() {}

func (x *SnapshotRequest_Setup) ProtoReflect() protoreflect.Message {
	mi := &file_machina_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SnapshotRequest_Setup.ProtoReflect.Descriptor instead.
func (*SnapshotRequest_Setup) Descriptor() ([]byte, []int) {
	return file_machina_proto_rawDescGZIP(), []int{3, 0}
}

func (x *SnapshotRequest_Setup) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *SnapshotRequest_Setup) GetProcessFingerprint() string {
	if x != nil {
		return x.ProcessFingerprint
	}
	return ""
}

// Snapshot is the second message from the client in the Snapshot protocol.
// It trggers the snapshot process.
type SnapshotRequest_Snapshot struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *SnapshotRequest_Snapshot) Reset() {
	*x = SnapshotRequest_Snapshot{}
	if protoimpl.UnsafeEnabled {
		mi := &file_machina_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SnapshotRequest_Snapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SnapshotRequest_Snapshot) ProtoMessage() {}

func (x *SnapshotRequest_Snapshot) ProtoReflect() protoreflect.Message {
	mi := &file_machina_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SnapshotRequest_Snapshot.ProtoReflect.Descriptor instead.
func (*SnapshotRequest_Snapshot) Descriptor() ([]byte, []int) {
	return file_machina_proto_rawDescGZIP(), []int{3, 1}
}

var File_machina_proto protoreflect.FileDescriptor

var file_machina_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x6d, 0x61, 0x63, 0x68, 0x69, 0x6e, 0x61, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x07, 0x6d, 0x61, 0x63, 0x68, 0x69, 0x6e, 0x61, 0x1a, 0x0d, 0x70, 0x72, 0x6f, 0x63, 0x65, 0x73,
	0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x0b, 0x63, 0x68, 0x75, 0x6e, 0x6b, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x52, 0x0a, 0x15, 0x57, 0x61, 0x74, 0x63, 0x68, 0x50, 0x72,
	0x6f, 0x63, 0x65, 0x73, 0x73, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x33,
	0x0a, 0x0b, 0x6c, 0x61, 0x62, 0x65, 0x6c, 0x5f, 0x72, 0x75, 0x6c, 0x65, 0x73, 0x18, 0x02, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x70, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x2e, 0x4c, 0x61,
	0x62, 0x65, 0x6c, 0x52, 0x75, 0x6c, 0x65, 0x52, 0x0a, 0x6c, 0x61, 0x62, 0x65, 0x6c, 0x52, 0x75,
	0x6c, 0x65, 0x73, 0x4a, 0x04, 0x08, 0x01, 0x10, 0x02, 0x22, 0x4a, 0x0a, 0x06, 0x55, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x12, 0x26, 0x0a, 0x05, 0x61, 0x64, 0x64, 0x65, 0x64, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x10, 0x2e, 0x70, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x2e, 0x50, 0x72, 0x6f,
	0x63, 0x65, 0x73, 0x73, 0x52, 0x05, 0x61, 0x64, 0x64, 0x65, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x72,
	0x65, 0x6d, 0x6f, 0x76, 0x65, 0x64, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x07, 0x72, 0x65,
	0x6d, 0x6f, 0x76, 0x65, 0x64, 0x22, 0x2a, 0x0a, 0x14, 0x47, 0x65, 0x74, 0x45, 0x78, 0x65, 0x63,
	0x75, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a,
	0x04, 0x68, 0x61, 0x73, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x68, 0x61, 0x73,
	0x68, 0x22, 0xed, 0x01, 0x0a, 0x0f, 0x53, 0x6e, 0x61, 0x70, 0x73, 0x68, 0x6f, 0x74, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x36, 0x0a, 0x05, 0x73, 0x65, 0x74, 0x75, 0x70, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x6d, 0x61, 0x63, 0x68, 0x69, 0x6e, 0x61, 0x2e, 0x53,
	0x6e, 0x61, 0x70, 0x73, 0x68, 0x6f, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x53,
	0x65, 0x74, 0x75, 0x70, 0x48, 0x00, 0x52, 0x05, 0x73, 0x65, 0x74, 0x75, 0x70, 0x12, 0x3f, 0x0a,
	0x08, 0x73, 0x6e, 0x61, 0x70, 0x73, 0x68, 0x6f, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x21, 0x2e, 0x6d, 0x61, 0x63, 0x68, 0x69, 0x6e, 0x61, 0x2e, 0x53, 0x6e, 0x61, 0x70, 0x73, 0x68,
	0x6f, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x53, 0x6e, 0x61, 0x70, 0x73, 0x68,
	0x6f, 0x74, 0x48, 0x00, 0x52, 0x08, 0x73, 0x6e, 0x61, 0x70, 0x73, 0x68, 0x6f, 0x74, 0x1a, 0x4a,
	0x0a, 0x05, 0x53, 0x65, 0x74, 0x75, 0x70, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x2f, 0x0a, 0x13, 0x70, 0x72, 0x6f,
	0x63, 0x65, 0x73, 0x73, 0x5f, 0x66, 0x69, 0x6e, 0x67, 0x65, 0x72, 0x70, 0x72, 0x69, 0x6e, 0x74,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x12, 0x70, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x46,
	0x69, 0x6e, 0x67, 0x65, 0x72, 0x70, 0x72, 0x69, 0x6e, 0x74, 0x1a, 0x0a, 0x0a, 0x08, 0x53, 0x6e,
	0x61, 0x70, 0x73, 0x68, 0x6f, 0x74, 0x42, 0x09, 0x0a, 0x07, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x22, 0x8c, 0x01, 0x0a, 0x10, 0x53, 0x6e, 0x61, 0x70, 0x73, 0x68, 0x6f, 0x74, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x12, 0x38, 0x0a, 0x09, 0x74, 0x69,
	0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e,
	0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e,
	0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73,
	0x74, 0x61, 0x6d, 0x70, 0x12, 0x2a, 0x0a, 0x11, 0x70, 0x61, 0x75, 0x73, 0x65, 0x5f, 0x64, 0x75,
	0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x6e, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x04, 0x52,
	0x0f, 0x70, 0x61, 0x75, 0x73, 0x65, 0x44, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4e, 0x73,
	0x22, 0x14, 0x0a, 0x12, 0x4d, 0x61, 0x63, 0x68, 0x69, 0x6e, 0x61, 0x49, 0x6e, 0x66, 0x6f, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0xd5, 0x01, 0x0a, 0x13, 0x4d, 0x61, 0x63, 0x68, 0x69,
	0x6e, 0x61, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x20,
	0x0a, 0x0b, 0x66, 0x69, 0x6e, 0x67, 0x65, 0x72, 0x70, 0x72, 0x69, 0x6e, 0x74, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0b, 0x66, 0x69, 0x6e, 0x67, 0x65, 0x72, 0x70, 0x72, 0x69, 0x6e, 0x74,
	0x12, 0x1a, 0x0a, 0x08, 0x68, 0x6f, 0x73, 0x74, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x08, 0x68, 0x6f, 0x73, 0x74, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07,
	0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x76,
	0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x21, 0x0a, 0x0c, 0x74, 0x65, 0x6e, 0x61, 0x6e, 0x74,
	0x5f, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x74, 0x65,
	0x6e, 0x61, 0x6e, 0x74, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x20, 0x0a, 0x0b, 0x65, 0x6e, 0x76,
	0x69, 0x72, 0x6f, 0x6e, 0x6d, 0x65, 0x6e, 0x74, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b,
	0x65, 0x6e, 0x76, 0x69, 0x72, 0x6f, 0x6e, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x21, 0x0a, 0x0c, 0x69,
	0x70, 0x5f, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x65, 0x73, 0x18, 0x07, 0x20, 0x03, 0x28,
	0x09, 0x52, 0x0b, 0x69, 0x70, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x65, 0x73, 0x32, 0xa7,
	0x02, 0x0a, 0x07, 0x4d, 0x61, 0x63, 0x68, 0x69, 0x6e, 0x61, 0x12, 0x45, 0x0a, 0x0e, 0x57, 0x61,
	0x74, 0x63, 0x68, 0x50, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x65, 0x73, 0x12, 0x1e, 0x2e, 0x6d,
	0x61, 0x63, 0x68, 0x69, 0x6e, 0x61, 0x2e, 0x57, 0x61, 0x74, 0x63, 0x68, 0x50, 0x72, 0x6f, 0x63,
	0x65, 0x73, 0x73, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x0f, 0x2e, 0x6d,
	0x61, 0x63, 0x68, 0x69, 0x6e, 0x61, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x22, 0x00, 0x30,
	0x01, 0x12, 0x40, 0x0a, 0x0d, 0x47, 0x65, 0x74, 0x45, 0x78, 0x65, 0x63, 0x75, 0x74, 0x61, 0x62,
	0x6c, 0x65, 0x12, 0x1d, 0x2e, 0x6d, 0x61, 0x63, 0x68, 0x69, 0x6e, 0x61, 0x2e, 0x47, 0x65, 0x74,
	0x45, 0x78, 0x65, 0x63, 0x75, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x0c, 0x2e, 0x63, 0x68, 0x75, 0x6e, 0x6b, 0x2e, 0x43, 0x68, 0x75, 0x6e, 0x6b, 0x22,
	0x00, 0x30, 0x01, 0x12, 0x45, 0x0a, 0x08, 0x53, 0x6e, 0x61, 0x70, 0x73, 0x68, 0x6f, 0x74, 0x12,
	0x18, 0x2e, 0x6d, 0x61, 0x63, 0x68, 0x69, 0x6e, 0x61, 0x2e, 0x53, 0x6e, 0x61, 0x70, 0x73, 0x68,
	0x6f, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x19, 0x2e, 0x6d, 0x61, 0x63, 0x68,
	0x69, 0x6e, 0x61, 0x2e, 0x53, 0x6e, 0x61, 0x70, 0x73, 0x68, 0x6f, 0x74, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x28, 0x01, 0x30, 0x01, 0x12, 0x4c, 0x0a, 0x0b, 0x4d, 0x61,
	0x63, 0x68, 0x69, 0x6e, 0x61, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x1b, 0x2e, 0x6d, 0x61, 0x63, 0x68,
	0x69, 0x6e, 0x61, 0x2e, 0x4d, 0x61, 0x63, 0x68, 0x69, 0x6e, 0x61, 0x49, 0x6e, 0x66, 0x6f, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1c, 0x2e, 0x6d, 0x61, 0x63, 0x68, 0x69, 0x6e, 0x61,
	0x2e, 0x4d, 0x61, 0x63, 0x68, 0x69, 0x6e, 0x61, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x30, 0x01, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_machina_proto_rawDescOnce sync.Once
	file_machina_proto_rawDescData = file_machina_proto_rawDesc
)

func file_machina_proto_rawDescGZIP() []byte {
	file_machina_proto_rawDescOnce.Do(func() {
		file_machina_proto_rawDescData = protoimpl.X.CompressGZIP(file_machina_proto_rawDescData)
	})
	return file_machina_proto_rawDescData
}

var file_machina_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_machina_proto_goTypes = []interface{}{
	(*WatchProcessesRequest)(nil),    // 0: machina.WatchProcessesRequest
	(*Update)(nil),                   // 1: machina.Update
	(*GetExecutableRequest)(nil),     // 2: machina.GetExecutableRequest
	(*SnapshotRequest)(nil),          // 3: machina.SnapshotRequest
	(*SnapshotResponse)(nil),         // 4: machina.SnapshotResponse
	(*MachinaInfoRequest)(nil),       // 5: machina.MachinaInfoRequest
	(*MachinaInfoResponse)(nil),      // 6: machina.MachinaInfoResponse
	(*SnapshotRequest_Setup)(nil),    // 7: machina.SnapshotRequest.Setup
	(*SnapshotRequest_Snapshot)(nil), // 8: machina.SnapshotRequest.Snapshot
	(*LabelRule)(nil),                // 9: process.LabelRule
	(*Process)(nil),                  // 10: process.Process
	(*timestamppb.Timestamp)(nil),    // 11: google.protobuf.Timestamp
	(*chunkpb.Chunk)(nil),            // 12: chunk.Chunk
}
var file_machina_proto_depIdxs = []int32{
	9,  // 0: machina.WatchProcessesRequest.label_rules:type_name -> process.LabelRule
	10, // 1: machina.Update.added:type_name -> process.Process
	7,  // 2: machina.SnapshotRequest.setup:type_name -> machina.SnapshotRequest.Setup
	8,  // 3: machina.SnapshotRequest.snapshot:type_name -> machina.SnapshotRequest.Snapshot
	11, // 4: machina.SnapshotResponse.timestamp:type_name -> google.protobuf.Timestamp
	0,  // 5: machina.Machina.WatchProcesses:input_type -> machina.WatchProcessesRequest
	2,  // 6: machina.Machina.GetExecutable:input_type -> machina.GetExecutableRequest
	3,  // 7: machina.Machina.Snapshot:input_type -> machina.SnapshotRequest
	5,  // 8: machina.Machina.MachinaInfo:input_type -> machina.MachinaInfoRequest
	1,  // 9: machina.Machina.WatchProcesses:output_type -> machina.Update
	12, // 10: machina.Machina.GetExecutable:output_type -> chunk.Chunk
	4,  // 11: machina.Machina.Snapshot:output_type -> machina.SnapshotResponse
	6,  // 12: machina.Machina.MachinaInfo:output_type -> machina.MachinaInfoResponse
	9,  // [9:13] is the sub-list for method output_type
	5,  // [5:9] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_machina_proto_init() }
func file_machina_proto_init() {
	if File_machina_proto != nil {
		return
	}
	file_process_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_machina_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WatchProcessesRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_machina_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Update); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_machina_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetExecutableRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_machina_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SnapshotRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_machina_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SnapshotResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_machina_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MachinaInfoRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_machina_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MachinaInfoResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_machina_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SnapshotRequest_Setup); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_machina_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SnapshotRequest_Snapshot); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_machina_proto_msgTypes[3].OneofWrappers = []interface{}{
		(*SnapshotRequest_Setup_)(nil),
		(*SnapshotRequest_Snapshot_)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_machina_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_machina_proto_goTypes,
		DependencyIndexes: file_machina_proto_depIdxs,
		MessageInfos:      file_machina_proto_msgTypes,
	}.Build()
	File_machina_proto = out.File
	file_machina_proto_rawDesc = nil
	file_machina_proto_goTypes = nil
	file_machina_proto_depIdxs = nil
}
