// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.1
// 	protoc        v3.21.12
// source: machina.proto

package machinapb

import (
	chunkpb "github.com/DataExMachina-dev/side-eye-go/internal/chunkpb"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WatchProcessesRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Predicates which are used to filter the processes. The resulting set will
	// be the disjunction of the predicates (OR).
	LabelRules []*LabelRule `protobuf:"bytes,2,rep,name=label_rules,json=labelRules,proto3" json:"label_rules,omitempty"`
}

func (x *WatchProcessesRequest) Reset() {
	*x = WatchProcessesRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_machina_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WatchProcessesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchProcessesRequest) ProtoMessage() {}

func (x *WatchProcessesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_machina_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchProcessesRequest.ProtoReflect.Descriptor instead.
func (*WatchProcessesRequest) Descriptor() ([]byte, []int) {
	return file_machina_proto_rawDescGZIP(), []int{0}
}

func (x *WatchProcessesRequest) GetLabelRules() []*LabelRule {
	if x != nil {
		return x.LabelRules
	}
	return nil
}

type Update struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The process which was updated.
	Added   []*Process `protobuf:"bytes,1,rep,name=added,proto3" json:"added,omitempty"`
	Removed []string   `protobuf:"bytes,2,rep,name=removed,proto3" json:"removed,omitempty"`
}

func (x *Update) Reset() {
	*x = Update{}
	if protoimpl.UnsafeEnabled {
		mi := &file_machina_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Update) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Update) ProtoMessage() {}

func (x *Update) ProtoReflect() protoreflect.Message {
	mi := &file_machina_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Update.ProtoReflect.Descriptor instead.
func (*Update) Descriptor() ([]byte, []int) {
	return file_machina_proto_rawDescGZIP(), []int{1}
}

func (x *Update) GetAdded() []*Process {
	if x != nil {
		return x.Added
	}
	return nil
}

func (x *Update) GetRemoved() []string {
	if x != nil {
		return x.Removed
	}
	return nil
}

type GetExecutableRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The path to the executable.
	Hash string `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
}

func (x *GetExecutableRequest) Reset() {
	*x = GetExecutableRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_machina_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetExecutableRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetExecutableRequest) ProtoMessage() {}

func (x *GetExecutableRequest) ProtoReflect() protoreflect.Message {
	mi := &file_machina_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetExecutableRequest.ProtoReflect.Descriptor instead.
func (*GetExecutableRequest) Descriptor() ([]byte, []int) {
	return file_machina_proto_rawDescGZIP(), []int{2}
}

func (x *GetExecutableRequest) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

// The SnapshotRequest drives the snapshot process.
type SnapshotRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Request:
	//
	//	*SnapshotRequest_Setup_
	//	*SnapshotRequest_Snapshot_
	Request isSnapshotRequest_Request `protobuf_oneof:"request"`
}

func (x *SnapshotRequest) Reset() {
	*x = SnapshotRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_machina_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SnapshotRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SnapshotRequest) ProtoMessage() {}

func (x *SnapshotRequest) ProtoReflect() protoreflect.Message {
	mi := &file_machina_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SnapshotRequest.ProtoReflect.Descriptor instead.
func (*SnapshotRequest) Descriptor() ([]byte, []int) {
	return file_machina_proto_rawDescGZIP(), []int{3}
}

func (m *SnapshotRequest) GetRequest() isSnapshotRequest_Request {
	if m != nil {
		return m.Request
	}
	return nil
}

func (x *SnapshotRequest) GetSetup() *SnapshotRequest_Setup {
	if x, ok := x.GetRequest().(*SnapshotRequest_Setup_); ok {
		return x.Setup
	}
	return nil
}

func (x *SnapshotRequest) GetSnapshot() *SnapshotRequest_Snapshot {
	if x, ok := x.GetRequest().(*SnapshotRequest_Snapshot_); ok {
		return x.Snapshot
	}
	return nil
}

type isSnapshotRequest_Request interface {
	isSnapshotRequest_Request()
}

type SnapshotRequest_Setup_ struct {
	Setup *SnapshotRequest_Setup `protobuf:"bytes,1,opt,name=setup,proto3,oneof"`
}

type SnapshotRequest_Snapshot_ struct {
	Snapshot *SnapshotRequest_Snapshot `protobuf:"bytes,2,opt,name=snapshot,proto3,oneof"`
}

func (*SnapshotRequest_Setup_) isSnapshotRequest_Request() {}

func (*SnapshotRequest_Snapshot_) isSnapshotRequest_Request() {}

type EventsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Request:
	//
	//	*EventsRequest_Setup_
	//	*EventsRequest_Stream_
	//	*EventsRequest_Finish_
	Request isEventsRequest_Request `protobuf_oneof:"request"`
}

func (x *EventsRequest) Reset() {
	*x = EventsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_machina_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EventsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventsRequest) ProtoMessage() {}

func (x *EventsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_machina_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventsRequest.ProtoReflect.Descriptor instead.
func (*EventsRequest) Descriptor() ([]byte, []int) {
	return file_machina_proto_rawDescGZIP(), []int{4}
}

func (m *EventsRequest) GetRequest() isEventsRequest_Request {
	if m != nil {
		return m.Request
	}
	return nil
}

func (x *EventsRequest) GetSetup() *EventsRequest_Setup {
	if x, ok := x.GetRequest().(*EventsRequest_Setup_); ok {
		return x.Setup
	}
	return nil
}

func (x *EventsRequest) GetStream() *EventsRequest_Stream {
	if x, ok := x.GetRequest().(*EventsRequest_Stream_); ok {
		return x.Stream
	}
	return nil
}

func (x *EventsRequest) GetFinish() *EventsRequest_Finish {
	if x, ok := x.GetRequest().(*EventsRequest_Finish_); ok {
		return x.Finish
	}
	return nil
}

type isEventsRequest_Request interface {
	isEventsRequest_Request()
}

type EventsRequest_Setup_ struct {
	Setup *EventsRequest_Setup `protobuf:"bytes,1,opt,name=setup,proto3,oneof"`
}

type EventsRequest_Stream_ struct {
	Stream *EventsRequest_Stream `protobuf:"bytes,2,opt,name=stream,proto3,oneof"`
}

type EventsRequest_Finish_ struct {
	Finish *EventsRequest_Finish `protobuf:"bytes,3,opt,name=finish,proto3,oneof"`
}

func (*EventsRequest_Setup_) isEventsRequest_Request() {}

func (*EventsRequest_Stream_) isEventsRequest_Request() {}

func (*EventsRequest_Finish_) isEventsRequest_Request() {}

type EventsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// TODO: Add a trailing message with statistics about the events.
	//
	// Types that are assignable to Response:
	//
	//	*EventsResponse_Event_
	//	*EventsResponse_ApproximateBootTime_
	//	*EventsResponse_Attached_
	//	*EventsResponse_Detached_
	Response isEventsResponse_Response `protobuf_oneof:"response"`
}

func (x *EventsResponse) Reset() {
	*x = EventsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_machina_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EventsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventsResponse) ProtoMessage() {}

func (x *EventsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_machina_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventsResponse.ProtoReflect.Descriptor instead.
func (*EventsResponse) Descriptor() ([]byte, []int) {
	return file_machina_proto_rawDescGZIP(), []int{5}
}

func (m *EventsResponse) GetResponse() isEventsResponse_Response {
	if m != nil {
		return m.Response
	}
	return nil
}

func (x *EventsResponse) GetEvent() *EventsResponse_Event {
	if x, ok := x.GetResponse().(*EventsResponse_Event_); ok {
		return x.Event
	}
	return nil
}

func (x *EventsResponse) GetApproximateBootTime() *EventsResponse_ApproximateBootTime {
	if x, ok := x.GetResponse().(*EventsResponse_ApproximateBootTime_); ok {
		return x.ApproximateBootTime
	}
	return nil
}

func (x *EventsResponse) GetAttached() *EventsResponse_Attached {
	if x, ok := x.GetResponse().(*EventsResponse_Attached_); ok {
		return x.Attached
	}
	return nil
}

func (x *EventsResponse) GetDetached() *EventsResponse_Detached {
	if x, ok := x.GetResponse().(*EventsResponse_Detached_); ok {
		return x.Detached
	}
	return nil
}

type isEventsResponse_Response interface {
	isEventsResponse_Response()
}

type EventsResponse_Event_ struct {
	Event *EventsResponse_Event `protobuf:"bytes,1,opt,name=event,proto3,oneof"`
}

type EventsResponse_ApproximateBootTime_ struct {
	ApproximateBootTime *EventsResponse_ApproximateBootTime `protobuf:"bytes,2,opt,name=approximate_boot_time,json=approximateBootTime,proto3,oneof"`
}

type EventsResponse_Attached_ struct {
	Attached *EventsResponse_Attached `protobuf:"bytes,3,opt,name=attached,proto3,oneof"`
}

type EventsResponse_Detached_ struct {
	Detached *EventsResponse_Detached `protobuf:"bytes,4,opt,name=detached,proto3,oneof"`
}

func (*EventsResponse_Event_) isEventsResponse_Response() {}

func (*EventsResponse_ApproximateBootTime_) isEventsResponse_Response() {}

func (*EventsResponse_Attached_) isEventsResponse_Response() {}

func (*EventsResponse_Detached_) isEventsResponse_Response() {}

type SnapshotResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data []byte `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	// The timestamp of the snapshot. This is a best-effort timestamp that
	// should closely match the time at which the snapshot was taken.
	Timestamp *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// The duration of the pause for the snapshot as observed by the agent.
	PauseDurationNs uint64 `protobuf:"varint,3,opt,name=pause_duration_ns,json=pauseDurationNs,proto3" json:"pause_duration_ns,omitempty"`
}

func (x *SnapshotResponse) Reset() {
	*x = SnapshotResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_machina_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SnapshotResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SnapshotResponse) ProtoMessage() {}

func (x *SnapshotResponse) ProtoReflect() protoreflect.Message {
	mi := &file_machina_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SnapshotResponse.ProtoReflect.Descriptor instead.
func (*SnapshotResponse) Descriptor() ([]byte, []int) {
	return file_machina_proto_rawDescGZIP(), []int{6}
}

func (x *SnapshotResponse) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *SnapshotResponse) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *SnapshotResponse) GetPauseDurationNs() uint64 {
	if x != nil {
		return x.PauseDurationNs
	}
	return 0
}

type MachinaInfoRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *MachinaInfoRequest) Reset() {
	*x = MachinaInfoRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_machina_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MachinaInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MachinaInfoRequest) ProtoMessage() {}

func (x *MachinaInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_machina_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MachinaInfoRequest.ProtoReflect.Descriptor instead.
func (*MachinaInfoRequest) Descriptor() ([]byte, []int) {
	return file_machina_proto_rawDescGZIP(), []int{7}
}

type MachinaInfoResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// A unique identifier for this machina.
	Fingerprint string `protobuf:"bytes,1,opt,name=fingerprint,proto3" json:"fingerprint,omitempty"`
	// The hostname of the machina.
	Hostname string `protobuf:"bytes,3,opt,name=hostname,proto3" json:"hostname,omitempty"`
	// The version of the machina.
	Version string `protobuf:"bytes,4,opt,name=version,proto3" json:"version,omitempty"`
	// The token of the tenant to which this machina belongs.
	//
	// TODO: Define any structure for this token. For now it's opaque and will
	// correspond to the token used to scope requests to a tenant.
	TenantToken string `protobuf:"bytes,5,opt,name=tenant_token,json=tenantToken,proto3" json:"tenant_token,omitempty"`
	// The environment flag passed to the machina.
	Environment string `protobuf:"bytes,6,opt,name=environment,proto3" json:"environment,omitempty"`
	// The IP addresses of the machina.
	IpAddresses []string `protobuf:"bytes,7,rep,name=ip_addresses,json=ipAddresses,proto3" json:"ip_addresses,omitempty"`
}

func (x *MachinaInfoResponse) Reset() {
	*x = MachinaInfoResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_machina_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MachinaInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MachinaInfoResponse) ProtoMessage() {}

func (x *MachinaInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_machina_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MachinaInfoResponse.ProtoReflect.Descriptor instead.
func (*MachinaInfoResponse) Descriptor() ([]byte, []int) {
	return file_machina_proto_rawDescGZIP(), []int{8}
}

func (x *MachinaInfoResponse) GetFingerprint() string {
	if x != nil {
		return x.Fingerprint
	}
	return ""
}

func (x *MachinaInfoResponse) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *MachinaInfoResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *MachinaInfoResponse) GetTenantToken() string {
	if x != nil {
		return x.TenantToken
	}
	return ""
}

func (x *MachinaInfoResponse) GetEnvironment() string {
	if x != nil {
		return x.Environment
	}
	return ""
}

func (x *MachinaInfoResponse) GetIpAddresses() []string {
	if x != nil {
		return x.IpAddresses
	}
	return nil
}

// Setup is the first message from the client in the Snapshot protocol.
type SnapshotRequest_Setup struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The key associated with the artifacts needed for this snapshot.
	Key string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	// The fingerprint of the process to snapshot.
	ProcessFingerprint string `protobuf:"bytes,2,opt,name=process_fingerprint,json=processFingerprint,proto3" json:"process_fingerprint,omitempty"`
}

func (x *SnapshotRequest_Setup) Reset() {
	*x = SnapshotRequest_Setup{}
	if protoimpl.UnsafeEnabled {
		mi := &file_machina_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SnapshotRequest_Setup) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SnapshotRequest_Setup) ProtoMessage() {}

func (x *SnapshotRequest_Setup) ProtoReflect() protoreflect.Message {
	mi := &file_machina_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SnapshotRequest_Setup.ProtoReflect.Descriptor instead.
func (*SnapshotRequest_Setup) Descriptor() ([]byte, []int) {
	return file_machina_proto_rawDescGZIP(), []int{3, 0}
}

func (x *SnapshotRequest_Setup) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *SnapshotRequest_Setup) GetProcessFingerprint() string {
	if x != nil {
		return x.ProcessFingerprint
	}
	return ""
}

// Snapshot is the second message from the client in the Snapshot protocol.
// It trggers the snapshot process.
type SnapshotRequest_Snapshot struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *SnapshotRequest_Snapshot) Reset() {
	*x = SnapshotRequest_Snapshot{}
	if protoimpl.UnsafeEnabled {
		mi := &file_machina_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SnapshotRequest_Snapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SnapshotRequest_Snapshot) ProtoMessage() {}

func (x *SnapshotRequest_Snapshot) ProtoReflect() protoreflect.Message {
	mi := &file_machina_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SnapshotRequest_Snapshot.ProtoReflect.Descriptor instead.
func (*SnapshotRequest_Snapshot) Descriptor() ([]byte, []int) {
	return file_machina_proto_rawDescGZIP(), []int{3, 1}
}

type EventsRequest_Setup struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The key associated with the artifacts needed for this snapshot.
	Key string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	// The fingerprint of the process to snapshot.
	ProcessFingerprint string `protobuf:"bytes,2,opt,name=process_fingerprint,json=processFingerprint,proto3" json:"process_fingerprint,omitempty"`
}

func (x *EventsRequest_Setup) Reset() {
	*x = EventsRequest_Setup{}
	if protoimpl.UnsafeEnabled {
		mi := &file_machina_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EventsRequest_Setup) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventsRequest_Setup) ProtoMessage() {}

func (x *EventsRequest_Setup) ProtoReflect() protoreflect.Message {
	mi := &file_machina_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventsRequest_Setup.ProtoReflect.Descriptor instead.
func (*EventsRequest_Setup) Descriptor() ([]byte, []int) {
	return file_machina_proto_rawDescGZIP(), []int{4, 0}
}

func (x *EventsRequest_Setup) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *EventsRequest_Setup) GetProcessFingerprint() string {
	if x != nil {
		return x.ProcessFingerprint
	}
	return ""
}

type EventsRequest_Stream struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The number of events to stream.
	MaxCount uint32 `protobuf:"varint,1,opt,name=max_count,json=maxCount,proto3" json:"max_count,omitempty"`
}

func (x *EventsRequest_Stream) Reset() {
	*x = EventsRequest_Stream{}
	if protoimpl.UnsafeEnabled {
		mi := &file_machina_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EventsRequest_Stream) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventsRequest_Stream) ProtoMessage() {}

func (x *EventsRequest_Stream) ProtoReflect() protoreflect.Message {
	mi := &file_machina_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventsRequest_Stream.ProtoReflect.Descriptor instead.
func (*EventsRequest_Stream) Descriptor() ([]byte, []int) {
	return file_machina_proto_rawDescGZIP(), []int{4, 1}
}

func (x *EventsRequest_Stream) GetMaxCount() uint32 {
	if x != nil {
		return x.MaxCount
	}
	return 0
}

type EventsRequest_Finish struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *EventsRequest_Finish) Reset() {
	*x = EventsRequest_Finish{}
	if protoimpl.UnsafeEnabled {
		mi := &file_machina_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EventsRequest_Finish) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventsRequest_Finish) ProtoMessage() {}

func (x *EventsRequest_Finish) ProtoReflect() protoreflect.Message {
	mi := &file_machina_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventsRequest_Finish.ProtoReflect.Descriptor instead.
func (*EventsRequest_Finish) Descriptor() ([]byte, []int) {
	return file_machina_proto_rawDescGZIP(), []int{4, 2}
}

type EventsResponse_Event struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data []byte `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *EventsResponse_Event) Reset() {
	*x = EventsResponse_Event{}
	if protoimpl.UnsafeEnabled {
		mi := &file_machina_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EventsResponse_Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventsResponse_Event) ProtoMessage() {}

func (x *EventsResponse_Event) ProtoReflect() protoreflect.Message {
	mi := &file_machina_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventsResponse_Event.ProtoReflect.Descriptor instead.
func (*EventsResponse_Event) Descriptor() ([]byte, []int) {
	return file_machina_proto_rawDescGZIP(), []int{5, 0}
}

func (x *EventsResponse_Event) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

// ApproximateBootTime is sent after the probes have been loaded.
// It is needed because bpf only has access to CLOCK_MONOTONIC time
// (at least until version 6.1 when bpf_ktime_get_tai_ns was introduced).
// This value is used to adjust the timestamp in the event to a wall clock
// timestamp. It will be approximate, but should be close enough.
type EventsResponse_ApproximateBootTime struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ApproximateBootTimeNs uint64 `protobuf:"varint,1,opt,name=approximate_boot_time_ns,json=approximateBootTimeNs,proto3" json:"approximate_boot_time_ns,omitempty"`
}

func (x *EventsResponse_ApproximateBootTime) Reset() {
	*x = EventsResponse_ApproximateBootTime{}
	if protoimpl.UnsafeEnabled {
		mi := &file_machina_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EventsResponse_ApproximateBootTime) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventsResponse_ApproximateBootTime) ProtoMessage() {}

func (x *EventsResponse_ApproximateBootTime) ProtoReflect() protoreflect.Message {
	mi := &file_machina_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventsResponse_ApproximateBootTime.ProtoReflect.Descriptor instead.
func (*EventsResponse_ApproximateBootTime) Descriptor() ([]byte, []int) {
	return file_machina_proto_rawDescGZIP(), []int{5, 1}
}

func (x *EventsResponse_ApproximateBootTime) GetApproximateBootTimeNs() uint64 {
	if x != nil {
		return x.ApproximateBootTimeNs
	}
	return 0
}

type EventsResponse_Attached struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *EventsResponse_Attached) Reset() {
	*x = EventsResponse_Attached{}
	if protoimpl.UnsafeEnabled {
		mi := &file_machina_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EventsResponse_Attached) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventsResponse_Attached) ProtoMessage() {}

func (x *EventsResponse_Attached) ProtoReflect() protoreflect.Message {
	mi := &file_machina_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventsResponse_Attached.ProtoReflect.Descriptor instead.
func (*EventsResponse_Attached) Descriptor() ([]byte, []int) {
	return file_machina_proto_rawDescGZIP(), []int{5, 2}
}

type EventsResponse_SummaryStatistics struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	EventsDroppedInEbpf      uint32 `protobuf:"varint,2,opt,name=events_dropped_in_ebpf,json=eventsDroppedInEbpf,proto3" json:"events_dropped_in_ebpf,omitempty"`
	EventsDroppedInUserspace uint32 `protobuf:"varint,3,opt,name=events_dropped_in_userspace,json=eventsDroppedInUserspace,proto3" json:"events_dropped_in_userspace,omitempty"`
}

func (x *EventsResponse_SummaryStatistics) Reset() {
	*x = EventsResponse_SummaryStatistics{}
	if protoimpl.UnsafeEnabled {
		mi := &file_machina_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EventsResponse_SummaryStatistics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventsResponse_SummaryStatistics) ProtoMessage() {}

func (x *EventsResponse_SummaryStatistics) ProtoReflect() protoreflect.Message {
	mi := &file_machina_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventsResponse_SummaryStatistics.ProtoReflect.Descriptor instead.
func (*EventsResponse_SummaryStatistics) Descriptor() ([]byte, []int) {
	return file_machina_proto_rawDescGZIP(), []int{5, 3}
}

func (x *EventsResponse_SummaryStatistics) GetEventsDroppedInEbpf() uint32 {
	if x != nil {
		return x.EventsDroppedInEbpf
	}
	return 0
}

func (x *EventsResponse_SummaryStatistics) GetEventsDroppedInUserspace() uint32 {
	if x != nil {
		return x.EventsDroppedInUserspace
	}
	return 0
}

type EventsResponse_Detached struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SummaryStatistics *EventsResponse_SummaryStatistics `protobuf:"bytes,1,opt,name=summary_statistics,json=summaryStatistics,proto3" json:"summary_statistics,omitempty"`
}

func (x *EventsResponse_Detached) Reset() {
	*x = EventsResponse_Detached{}
	if protoimpl.UnsafeEnabled {
		mi := &file_machina_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EventsResponse_Detached) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventsResponse_Detached) ProtoMessage() {}

func (x *EventsResponse_Detached) ProtoReflect() protoreflect.Message {
	mi := &file_machina_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventsResponse_Detached.ProtoReflect.Descriptor instead.
func (*EventsResponse_Detached) Descriptor() ([]byte, []int) {
	return file_machina_proto_rawDescGZIP(), []int{5, 4}
}

func (x *EventsResponse_Detached) GetSummaryStatistics() *EventsResponse_SummaryStatistics {
	if x != nil {
		return x.SummaryStatistics
	}
	return nil
}

var File_machina_proto protoreflect.FileDescriptor

var file_machina_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x6d, 0x61, 0x63, 0x68, 0x69, 0x6e, 0x61, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x07, 0x6d, 0x61, 0x63, 0x68, 0x69, 0x6e, 0x61, 0x1a, 0x0d, 0x70, 0x72, 0x6f, 0x63, 0x65, 0x73,
	0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x0b, 0x63, 0x68, 0x75, 0x6e, 0x6b, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x52, 0x0a, 0x15, 0x57, 0x61, 0x74, 0x63, 0x68, 0x50, 0x72,
	0x6f, 0x63, 0x65, 0x73, 0x73, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x33,
	0x0a, 0x0b, 0x6c, 0x61, 0x62, 0x65, 0x6c, 0x5f, 0x72, 0x75, 0x6c, 0x65, 0x73, 0x18, 0x02, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x70, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x2e, 0x4c, 0x61,
	0x62, 0x65, 0x6c, 0x52, 0x75, 0x6c, 0x65, 0x52, 0x0a, 0x6c, 0x61, 0x62, 0x65, 0x6c, 0x52, 0x75,
	0x6c, 0x65, 0x73, 0x4a, 0x04, 0x08, 0x01, 0x10, 0x02, 0x22, 0x4a, 0x0a, 0x06, 0x55, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x12, 0x26, 0x0a, 0x05, 0x61, 0x64, 0x64, 0x65, 0x64, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x10, 0x2e, 0x70, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x2e, 0x50, 0x72, 0x6f,
	0x63, 0x65, 0x73, 0x73, 0x52, 0x05, 0x61, 0x64, 0x64, 0x65, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x72,
	0x65, 0x6d, 0x6f, 0x76, 0x65, 0x64, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x07, 0x72, 0x65,
	0x6d, 0x6f, 0x76, 0x65, 0x64, 0x22, 0x2a, 0x0a, 0x14, 0x47, 0x65, 0x74, 0x45, 0x78, 0x65, 0x63,
	0x75, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a,
	0x04, 0x68, 0x61, 0x73, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x68, 0x61, 0x73,
	0x68, 0x22, 0xed, 0x01, 0x0a, 0x0f, 0x53, 0x6e, 0x61, 0x70, 0x73, 0x68, 0x6f, 0x74, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x36, 0x0a, 0x05, 0x73, 0x65, 0x74, 0x75, 0x70, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x6d, 0x61, 0x63, 0x68, 0x69, 0x6e, 0x61, 0x2e, 0x53,
	0x6e, 0x61, 0x70, 0x73, 0x68, 0x6f, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x53,
	0x65, 0x74, 0x75, 0x70, 0x48, 0x00, 0x52, 0x05, 0x73, 0x65, 0x74, 0x75, 0x70, 0x12, 0x3f, 0x0a,
	0x08, 0x73, 0x6e, 0x61, 0x70, 0x73, 0x68, 0x6f, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x21, 0x2e, 0x6d, 0x61, 0x63, 0x68, 0x69, 0x6e, 0x61, 0x2e, 0x53, 0x6e, 0x61, 0x70, 0x73, 0x68,
	0x6f, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x53, 0x6e, 0x61, 0x70, 0x73, 0x68,
	0x6f, 0x74, 0x48, 0x00, 0x52, 0x08, 0x73, 0x6e, 0x61, 0x70, 0x73, 0x68, 0x6f, 0x74, 0x1a, 0x4a,
	0x0a, 0x05, 0x53, 0x65, 0x74, 0x75, 0x70, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x2f, 0x0a, 0x13, 0x70, 0x72, 0x6f,
	0x63, 0x65, 0x73, 0x73, 0x5f, 0x66, 0x69, 0x6e, 0x67, 0x65, 0x72, 0x70, 0x72, 0x69, 0x6e, 0x74,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x12, 0x70, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x46,
	0x69, 0x6e, 0x67, 0x65, 0x72, 0x70, 0x72, 0x69, 0x6e, 0x74, 0x1a, 0x0a, 0x0a, 0x08, 0x53, 0x6e,
	0x61, 0x70, 0x73, 0x68, 0x6f, 0x74, 0x42, 0x09, 0x0a, 0x07, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x22, 0xbf, 0x02, 0x0a, 0x0d, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x34, 0x0a, 0x05, 0x73, 0x65, 0x74, 0x75, 0x70, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x6d, 0x61, 0x63, 0x68, 0x69, 0x6e, 0x61, 0x2e, 0x45, 0x76, 0x65,
	0x6e, 0x74, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x53, 0x65, 0x74, 0x75, 0x70,
	0x48, 0x00, 0x52, 0x05, 0x73, 0x65, 0x74, 0x75, 0x70, 0x12, 0x37, 0x0a, 0x06, 0x73, 0x74, 0x72,
	0x65, 0x61, 0x6d, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x6d, 0x61, 0x63, 0x68,
	0x69, 0x6e, 0x61, 0x2e, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x2e, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x48, 0x00, 0x52, 0x06, 0x73, 0x74, 0x72, 0x65,
	0x61, 0x6d, 0x12, 0x37, 0x0a, 0x06, 0x66, 0x69, 0x6e, 0x69, 0x73, 0x68, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x6d, 0x61, 0x63, 0x68, 0x69, 0x6e, 0x61, 0x2e, 0x45, 0x76, 0x65,
	0x6e, 0x74, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x46, 0x69, 0x6e, 0x69, 0x73,
	0x68, 0x48, 0x00, 0x52, 0x06, 0x66, 0x69, 0x6e, 0x69, 0x73, 0x68, 0x1a, 0x4a, 0x0a, 0x05, 0x53,
	0x65, 0x74, 0x75, 0x70, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x2f, 0x0a, 0x13, 0x70, 0x72, 0x6f, 0x63, 0x65, 0x73,
	0x73, 0x5f, 0x66, 0x69, 0x6e, 0x67, 0x65, 0x72, 0x70, 0x72, 0x69, 0x6e, 0x74, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x12, 0x70, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x46, 0x69, 0x6e, 0x67,
	0x65, 0x72, 0x70, 0x72, 0x69, 0x6e, 0x74, 0x1a, 0x25, 0x0a, 0x06, 0x53, 0x74, 0x72, 0x65, 0x61,
	0x6d, 0x12, 0x1b, 0x0a, 0x09, 0x6d, 0x61, 0x78, 0x5f, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0d, 0x52, 0x08, 0x6d, 0x61, 0x78, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x1a, 0x08,
	0x0a, 0x06, 0x46, 0x69, 0x6e, 0x69, 0x73, 0x68, 0x42, 0x09, 0x0a, 0x07, 0x72, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x22, 0x9f, 0x05, 0x0a, 0x0e, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x35, 0x0a, 0x05, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x6d, 0x61, 0x63, 0x68, 0x69, 0x6e, 0x61, 0x2e,
	0x45, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x45,
	0x76, 0x65, 0x6e, 0x74, 0x48, 0x00, 0x52, 0x05, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x12, 0x61, 0x0a,
	0x15, 0x61, 0x70, 0x70, 0x72, 0x6f, 0x78, 0x69, 0x6d, 0x61, 0x74, 0x65, 0x5f, 0x62, 0x6f, 0x6f,
	0x74, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x2b, 0x2e, 0x6d,
	0x61, 0x63, 0x68, 0x69, 0x6e, 0x61, 0x2e, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x41, 0x70, 0x70, 0x72, 0x6f, 0x78, 0x69, 0x6d, 0x61, 0x74,
	0x65, 0x42, 0x6f, 0x6f, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x48, 0x00, 0x52, 0x13, 0x61, 0x70, 0x70,
	0x72, 0x6f, 0x78, 0x69, 0x6d, 0x61, 0x74, 0x65, 0x42, 0x6f, 0x6f, 0x74, 0x54, 0x69, 0x6d, 0x65,
	0x12, 0x3e, 0x0a, 0x08, 0x61, 0x74, 0x74, 0x61, 0x63, 0x68, 0x65, 0x64, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x20, 0x2e, 0x6d, 0x61, 0x63, 0x68, 0x69, 0x6e, 0x61, 0x2e, 0x45, 0x76, 0x65,
	0x6e, 0x74, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x41, 0x74, 0x74, 0x61,
	0x63, 0x68, 0x65, 0x64, 0x48, 0x00, 0x52, 0x08, 0x61, 0x74, 0x74, 0x61, 0x63, 0x68, 0x65, 0x64,
	0x12, 0x3e, 0x0a, 0x08, 0x64, 0x65, 0x74, 0x61, 0x63, 0x68, 0x65, 0x64, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x20, 0x2e, 0x6d, 0x61, 0x63, 0x68, 0x69, 0x6e, 0x61, 0x2e, 0x45, 0x76, 0x65,
	0x6e, 0x74, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x44, 0x65, 0x74, 0x61,
	0x63, 0x68, 0x65, 0x64, 0x48, 0x00, 0x52, 0x08, 0x64, 0x65, 0x74, 0x61, 0x63, 0x68, 0x65, 0x64,
	0x1a, 0x1b, 0x0a, 0x05, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74,
	0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x1a, 0x4e, 0x0a,
	0x13, 0x41, 0x70, 0x70, 0x72, 0x6f, 0x78, 0x69, 0x6d, 0x61, 0x74, 0x65, 0x42, 0x6f, 0x6f, 0x74,
	0x54, 0x69, 0x6d, 0x65, 0x12, 0x37, 0x0a, 0x18, 0x61, 0x70, 0x70, 0x72, 0x6f, 0x78, 0x69, 0x6d,
	0x61, 0x74, 0x65, 0x5f, 0x62, 0x6f, 0x6f, 0x74, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x5f, 0x6e, 0x73,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x15, 0x61, 0x70, 0x70, 0x72, 0x6f, 0x78, 0x69, 0x6d,
	0x61, 0x74, 0x65, 0x42, 0x6f, 0x6f, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x4e, 0x73, 0x1a, 0x0a, 0x0a,
	0x08, 0x41, 0x74, 0x74, 0x61, 0x63, 0x68, 0x65, 0x64, 0x1a, 0x87, 0x01, 0x0a, 0x11, 0x53, 0x75,
	0x6d, 0x6d, 0x61, 0x72, 0x79, 0x53, 0x74, 0x61, 0x74, 0x69, 0x73, 0x74, 0x69, 0x63, 0x73, 0x12,
	0x33, 0x0a, 0x16, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x5f, 0x64, 0x72, 0x6f, 0x70, 0x70, 0x65,
	0x64, 0x5f, 0x69, 0x6e, 0x5f, 0x65, 0x62, 0x70, 0x66, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52,
	0x13, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x44, 0x72, 0x6f, 0x70, 0x70, 0x65, 0x64, 0x49, 0x6e,
	0x45, 0x62, 0x70, 0x66, 0x12, 0x3d, 0x0a, 0x1b, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x5f, 0x64,
	0x72, 0x6f, 0x70, 0x70, 0x65, 0x64, 0x5f, 0x69, 0x6e, 0x5f, 0x75, 0x73, 0x65, 0x72, 0x73, 0x70,
	0x61, 0x63, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x18, 0x65, 0x76, 0x65, 0x6e, 0x74,
	0x73, 0x44, 0x72, 0x6f, 0x70, 0x70, 0x65, 0x64, 0x49, 0x6e, 0x55, 0x73, 0x65, 0x72, 0x73, 0x70,
	0x61, 0x63, 0x65, 0x1a, 0x64, 0x0a, 0x08, 0x44, 0x65, 0x74, 0x61, 0x63, 0x68, 0x65, 0x64, 0x12,
	0x58, 0x0a, 0x12, 0x73, 0x75, 0x6d, 0x6d, 0x61, 0x72, 0x79, 0x5f, 0x73, 0x74, 0x61, 0x74, 0x69,
	0x73, 0x74, 0x69, 0x63, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x29, 0x2e, 0x6d, 0x61,
	0x63, 0x68, 0x69, 0x6e, 0x61, 0x2e, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x53, 0x75, 0x6d, 0x6d, 0x61, 0x72, 0x79, 0x53, 0x74, 0x61, 0x74,
	0x69, 0x73, 0x74, 0x69, 0x63, 0x73, 0x52, 0x11, 0x73, 0x75, 0x6d, 0x6d, 0x61, 0x72, 0x79, 0x53,
	0x74, 0x61, 0x74, 0x69, 0x73, 0x74, 0x69, 0x63, 0x73, 0x42, 0x0a, 0x0a, 0x08, 0x72, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x8c, 0x01, 0x0a, 0x10, 0x53, 0x6e, 0x61, 0x70, 0x73, 0x68,
	0x6f, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61,
	0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x12, 0x38,
	0x0a, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x09, 0x74,
	0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x12, 0x2a, 0x0a, 0x11, 0x70, 0x61, 0x75, 0x73,
	0x65, 0x5f, 0x64, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x6e, 0x73, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x04, 0x52, 0x0f, 0x70, 0x61, 0x75, 0x73, 0x65, 0x44, 0x75, 0x72, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x4e, 0x73, 0x22, 0x14, 0x0a, 0x12, 0x4d, 0x61, 0x63, 0x68, 0x69, 0x6e, 0x61, 0x49,
	0x6e, 0x66, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0xd5, 0x01, 0x0a, 0x13, 0x4d,
	0x61, 0x63, 0x68, 0x69, 0x6e, 0x61, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x66, 0x69, 0x6e, 0x67, 0x65, 0x72, 0x70, 0x72, 0x69, 0x6e,
	0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x66, 0x69, 0x6e, 0x67, 0x65, 0x72, 0x70,
	0x72, 0x69, 0x6e, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x68, 0x6f, 0x73, 0x74, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x68, 0x6f, 0x73, 0x74, 0x6e, 0x61, 0x6d, 0x65,
	0x12, 0x18, 0x0a, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x21, 0x0a, 0x0c, 0x74, 0x65,
	0x6e, 0x61, 0x6e, 0x74, 0x5f, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0b, 0x74, 0x65, 0x6e, 0x61, 0x6e, 0x74, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x20, 0x0a,
	0x0b, 0x65, 0x6e, 0x76, 0x69, 0x72, 0x6f, 0x6e, 0x6d, 0x65, 0x6e, 0x74, 0x18, 0x06, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0b, 0x65, 0x6e, 0x76, 0x69, 0x72, 0x6f, 0x6e, 0x6d, 0x65, 0x6e, 0x74, 0x12,
	0x21, 0x0a, 0x0c, 0x69, 0x70, 0x5f, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x65, 0x73, 0x18,
	0x07, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0b, 0x69, 0x70, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73,
	0x65, 0x73, 0x32, 0xe8, 0x02, 0x0a, 0x07, 0x4d, 0x61, 0x63, 0x68, 0x69, 0x6e, 0x61, 0x12, 0x45,
	0x0a, 0x0e, 0x57, 0x61, 0x74, 0x63, 0x68, 0x50, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x65, 0x73,
	0x12, 0x1e, 0x2e, 0x6d, 0x61, 0x63, 0x68, 0x69, 0x6e, 0x61, 0x2e, 0x57, 0x61, 0x74, 0x63, 0x68,
	0x50, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x0f, 0x2e, 0x6d, 0x61, 0x63, 0x68, 0x69, 0x6e, 0x61, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x22, 0x00, 0x30, 0x01, 0x12, 0x40, 0x0a, 0x0d, 0x47, 0x65, 0x74, 0x45, 0x78, 0x65, 0x63,
	0x75, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x12, 0x1d, 0x2e, 0x6d, 0x61, 0x63, 0x68, 0x69, 0x6e, 0x61,
	0x2e, 0x47, 0x65, 0x74, 0x45, 0x78, 0x65, 0x63, 0x75, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x0c, 0x2e, 0x63, 0x68, 0x75, 0x6e, 0x6b, 0x2e, 0x43, 0x68,
	0x75, 0x6e, 0x6b, 0x22, 0x00, 0x30, 0x01, 0x12, 0x45, 0x0a, 0x08, 0x53, 0x6e, 0x61, 0x70, 0x73,
	0x68, 0x6f, 0x74, 0x12, 0x18, 0x2e, 0x6d, 0x61, 0x63, 0x68, 0x69, 0x6e, 0x61, 0x2e, 0x53, 0x6e,
	0x61, 0x70, 0x73, 0x68, 0x6f, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x19, 0x2e,
	0x6d, 0x61, 0x63, 0x68, 0x69, 0x6e, 0x61, 0x2e, 0x53, 0x6e, 0x61, 0x70, 0x73, 0x68, 0x6f, 0x74,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x28, 0x01, 0x30, 0x01, 0x12, 0x3f,
	0x0a, 0x06, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x12, 0x16, 0x2e, 0x6d, 0x61, 0x63, 0x68, 0x69,
	0x6e, 0x61, 0x2e, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x17, 0x2e, 0x6d, 0x61, 0x63, 0x68, 0x69, 0x6e, 0x61, 0x2e, 0x45, 0x76, 0x65, 0x6e, 0x74,
	0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x28, 0x01, 0x30, 0x01, 0x12,
	0x4c, 0x0a, 0x0b, 0x4d, 0x61, 0x63, 0x68, 0x69, 0x6e, 0x61, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x1b,
	0x2e, 0x6d, 0x61, 0x63, 0x68, 0x69, 0x6e, 0x61, 0x2e, 0x4d, 0x61, 0x63, 0x68, 0x69, 0x6e, 0x61,
	0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1c, 0x2e, 0x6d, 0x61,
	0x63, 0x68, 0x69, 0x6e, 0x61, 0x2e, 0x4d, 0x61, 0x63, 0x68, 0x69, 0x6e, 0x61, 0x49, 0x6e, 0x66,
	0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x30, 0x01, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_machina_proto_rawDescOnce sync.Once
	file_machina_proto_rawDescData = file_machina_proto_rawDesc
)

func file_machina_proto_rawDescGZIP() []byte {
	file_machina_proto_rawDescOnce.Do(func() {
		file_machina_proto_rawDescData = protoimpl.X.CompressGZIP(file_machina_proto_rawDescData)
	})
	return file_machina_proto_rawDescData
}

var file_machina_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_machina_proto_goTypes = []interface{}{
	(*WatchProcessesRequest)(nil),              // 0: machina.WatchProcessesRequest
	(*Update)(nil),                             // 1: machina.Update
	(*GetExecutableRequest)(nil),               // 2: machina.GetExecutableRequest
	(*SnapshotRequest)(nil),                    // 3: machina.SnapshotRequest
	(*EventsRequest)(nil),                      // 4: machina.EventsRequest
	(*EventsResponse)(nil),                     // 5: machina.EventsResponse
	(*SnapshotResponse)(nil),                   // 6: machina.SnapshotResponse
	(*MachinaInfoRequest)(nil),                 // 7: machina.MachinaInfoRequest
	(*MachinaInfoResponse)(nil),                // 8: machina.MachinaInfoResponse
	(*SnapshotRequest_Setup)(nil),              // 9: machina.SnapshotRequest.Setup
	(*SnapshotRequest_Snapshot)(nil),           // 10: machina.SnapshotRequest.Snapshot
	(*EventsRequest_Setup)(nil),                // 11: machina.EventsRequest.Setup
	(*EventsRequest_Stream)(nil),               // 12: machina.EventsRequest.Stream
	(*EventsRequest_Finish)(nil),               // 13: machina.EventsRequest.Finish
	(*EventsResponse_Event)(nil),               // 14: machina.EventsResponse.Event
	(*EventsResponse_ApproximateBootTime)(nil), // 15: machina.EventsResponse.ApproximateBootTime
	(*EventsResponse_Attached)(nil),            // 16: machina.EventsResponse.Attached
	(*EventsResponse_SummaryStatistics)(nil),   // 17: machina.EventsResponse.SummaryStatistics
	(*EventsResponse_Detached)(nil),            // 18: machina.EventsResponse.Detached
	(*LabelRule)(nil),                          // 19: process.LabelRule
	(*Process)(nil),                            // 20: process.Process
	(*timestamppb.Timestamp)(nil),              // 21: google.protobuf.Timestamp
	(*chunkpb.Chunk)(nil),                      // 22: chunk.Chunk
}
var file_machina_proto_depIdxs = []int32{
	19, // 0: machina.WatchProcessesRequest.label_rules:type_name -> process.LabelRule
	20, // 1: machina.Update.added:type_name -> process.Process
	9,  // 2: machina.SnapshotRequest.setup:type_name -> machina.SnapshotRequest.Setup
	10, // 3: machina.SnapshotRequest.snapshot:type_name -> machina.SnapshotRequest.Snapshot
	11, // 4: machina.EventsRequest.setup:type_name -> machina.EventsRequest.Setup
	12, // 5: machina.EventsRequest.stream:type_name -> machina.EventsRequest.Stream
	13, // 6: machina.EventsRequest.finish:type_name -> machina.EventsRequest.Finish
	14, // 7: machina.EventsResponse.event:type_name -> machina.EventsResponse.Event
	15, // 8: machina.EventsResponse.approximate_boot_time:type_name -> machina.EventsResponse.ApproximateBootTime
	16, // 9: machina.EventsResponse.attached:type_name -> machina.EventsResponse.Attached
	18, // 10: machina.EventsResponse.detached:type_name -> machina.EventsResponse.Detached
	21, // 11: machina.SnapshotResponse.timestamp:type_name -> google.protobuf.Timestamp
	17, // 12: machina.EventsResponse.Detached.summary_statistics:type_name -> machina.EventsResponse.SummaryStatistics
	0,  // 13: machina.Machina.WatchProcesses:input_type -> machina.WatchProcessesRequest
	2,  // 14: machina.Machina.GetExecutable:input_type -> machina.GetExecutableRequest
	3,  // 15: machina.Machina.Snapshot:input_type -> machina.SnapshotRequest
	4,  // 16: machina.Machina.Events:input_type -> machina.EventsRequest
	7,  // 17: machina.Machina.MachinaInfo:input_type -> machina.MachinaInfoRequest
	1,  // 18: machina.Machina.WatchProcesses:output_type -> machina.Update
	22, // 19: machina.Machina.GetExecutable:output_type -> chunk.Chunk
	6,  // 20: machina.Machina.Snapshot:output_type -> machina.SnapshotResponse
	5,  // 21: machina.Machina.Events:output_type -> machina.EventsResponse
	8,  // 22: machina.Machina.MachinaInfo:output_type -> machina.MachinaInfoResponse
	18, // [18:23] is the sub-list for method output_type
	13, // [13:18] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_machina_proto_init() }
func file_machina_proto_init() {
	if File_machina_proto != nil {
		return
	}
	file_process_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_machina_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WatchProcessesRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_machina_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Update); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_machina_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetExecutableRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_machina_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SnapshotRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_machina_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EventsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_machina_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EventsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_machina_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SnapshotResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_machina_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MachinaInfoRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_machina_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MachinaInfoResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_machina_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SnapshotRequest_Setup); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_machina_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SnapshotRequest_Snapshot); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_machina_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EventsRequest_Setup); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_machina_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EventsRequest_Stream); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_machina_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EventsRequest_Finish); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_machina_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EventsResponse_Event); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_machina_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EventsResponse_ApproximateBootTime); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_machina_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EventsResponse_Attached); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_machina_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EventsResponse_SummaryStatistics); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_machina_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EventsResponse_Detached); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_machina_proto_msgTypes[3].OneofWrappers = []interface{}{
		(*SnapshotRequest_Setup_)(nil),
		(*SnapshotRequest_Snapshot_)(nil),
	}
	file_machina_proto_msgTypes[4].OneofWrappers = []interface{}{
		(*EventsRequest_Setup_)(nil),
		(*EventsRequest_Stream_)(nil),
		(*EventsRequest_Finish_)(nil),
	}
	file_machina_proto_msgTypes[5].OneofWrappers = []interface{}{
		(*EventsResponse_Event_)(nil),
		(*EventsResponse_ApproximateBootTime_)(nil),
		(*EventsResponse_Attached_)(nil),
		(*EventsResponse_Detached_)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_machina_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_machina_proto_goTypes,
		DependencyIndexes: file_machina_proto_depIdxs,
		MessageInfos:      file_machina_proto_msgTypes,
	}.Build()
	File_machina_proto = out.File
	file_machina_proto_rawDesc = nil
	file_machina_proto_goTypes = nil
	file_machina_proto_depIdxs = nil
}
