// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.1
// 	protoc        v3.21.12
// source: machina.proto

package machinapb

import (
	chunkpb "github.com/DataExMachina-dev/side-eye-go/internal/chunkpb"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ArrowIpcMessage_Kind int32

const (
	ArrowIpcMessage_UNKNOWN                        ArrowIpcMessage_Kind = 0
	ArrowIpcMessage_SCHEMA_WITH_DICTIONARY_TRACKER ArrowIpcMessage_Kind = 1
	ArrowIpcMessage_DICTIONARY_BATCH               ArrowIpcMessage_Kind = 2
	ArrowIpcMessage_RECORD_BATCH                   ArrowIpcMessage_Kind = 3
)

// Enum value maps for ArrowIpcMessage_Kind.
var (
	ArrowIpcMessage_Kind_name = map[int32]string{
		0: "UNKNOWN",
		1: "SCHEMA_WITH_DICTIONARY_TRACKER",
		2: "DICTIONARY_BATCH",
		3: "RECORD_BATCH",
	}
	ArrowIpcMessage_Kind_value = map[string]int32{
		"UNKNOWN":                        0,
		"SCHEMA_WITH_DICTIONARY_TRACKER": 1,
		"DICTIONARY_BATCH":               2,
		"RECORD_BATCH":                   3,
	}
)

func (x ArrowIpcMessage_Kind) Enum() *ArrowIpcMessage_Kind {
	p := new(ArrowIpcMessage_Kind)
	*p = x
	return p
}

func (x ArrowIpcMessage_Kind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ArrowIpcMessage_Kind) Descriptor() protoreflect.EnumDescriptor {
	return file_machina_proto_enumTypes[0].Descriptor()
}

func (ArrowIpcMessage_Kind) Type() protoreflect.EnumType {
	return &file_machina_proto_enumTypes[0]
}

func (x ArrowIpcMessage_Kind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ArrowIpcMessage_Kind.Descriptor instead.
func (ArrowIpcMessage_Kind) EnumDescriptor() ([]byte, []int) {
	return file_machina_proto_rawDescGZIP(), []int{6, 0}
}

type WatchProcessesRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Predicates which are used to filter the processes. The resulting set will
	// be the disjunction of the predicates (OR).
	LabelRules []*LabelRule `protobuf:"bytes,2,rep,name=label_rules,json=labelRules,proto3" json:"label_rules,omitempty"`
}

func (x *WatchProcessesRequest) Reset() {
	*x = WatchProcessesRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_machina_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WatchProcessesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchProcessesRequest) ProtoMessage() {}

func (x *WatchProcessesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_machina_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchProcessesRequest.ProtoReflect.Descriptor instead.
func (*WatchProcessesRequest) Descriptor() ([]byte, []int) {
	return file_machina_proto_rawDescGZIP(), []int{0}
}

func (x *WatchProcessesRequest) GetLabelRules() []*LabelRule {
	if x != nil {
		return x.LabelRules
	}
	return nil
}

type Update struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The process which was updated.
	Added   []*Process `protobuf:"bytes,1,rep,name=added,proto3" json:"added,omitempty"`
	Removed []string   `protobuf:"bytes,2,rep,name=removed,proto3" json:"removed,omitempty"`
	// Indicates that the update is incomplete. This is used to indicate that
	// the agent is paginating its processes list and the current set is not
	// a complete list.
	Incomplete bool `protobuf:"varint,3,opt,name=incomplete,proto3" json:"incomplete,omitempty"`
}

func (x *Update) Reset() {
	*x = Update{}
	if protoimpl.UnsafeEnabled {
		mi := &file_machina_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Update) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Update) ProtoMessage() {}

func (x *Update) ProtoReflect() protoreflect.Message {
	mi := &file_machina_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Update.ProtoReflect.Descriptor instead.
func (*Update) Descriptor() ([]byte, []int) {
	return file_machina_proto_rawDescGZIP(), []int{1}
}

func (x *Update) GetAdded() []*Process {
	if x != nil {
		return x.Added
	}
	return nil
}

func (x *Update) GetRemoved() []string {
	if x != nil {
		return x.Removed
	}
	return nil
}

func (x *Update) GetIncomplete() bool {
	if x != nil {
		return x.Incomplete
	}
	return false
}

type GetExecutableRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The path to the executable.
	Hash string `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
}

func (x *GetExecutableRequest) Reset() {
	*x = GetExecutableRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_machina_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetExecutableRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetExecutableRequest) ProtoMessage() {}

func (x *GetExecutableRequest) ProtoReflect() protoreflect.Message {
	mi := &file_machina_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetExecutableRequest.ProtoReflect.Descriptor instead.
func (*GetExecutableRequest) Descriptor() ([]byte, []int) {
	return file_machina_proto_rawDescGZIP(), []int{2}
}

func (x *GetExecutableRequest) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

// The SnapshotRequest drives the snapshot process.
type SnapshotRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Request:
	//
	//	*SnapshotRequest_Setup_
	//	*SnapshotRequest_Snapshot_
	Request isSnapshotRequest_Request `protobuf_oneof:"request"`
}

func (x *SnapshotRequest) Reset() {
	*x = SnapshotRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_machina_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SnapshotRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SnapshotRequest) ProtoMessage() {}

func (x *SnapshotRequest) ProtoReflect() protoreflect.Message {
	mi := &file_machina_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SnapshotRequest.ProtoReflect.Descriptor instead.
func (*SnapshotRequest) Descriptor() ([]byte, []int) {
	return file_machina_proto_rawDescGZIP(), []int{3}
}

func (m *SnapshotRequest) GetRequest() isSnapshotRequest_Request {
	if m != nil {
		return m.Request
	}
	return nil
}

func (x *SnapshotRequest) GetSetup() *SnapshotRequest_Setup {
	if x, ok := x.GetRequest().(*SnapshotRequest_Setup_); ok {
		return x.Setup
	}
	return nil
}

func (x *SnapshotRequest) GetSnapshot() *SnapshotRequest_Snapshot {
	if x, ok := x.GetRequest().(*SnapshotRequest_Snapshot_); ok {
		return x.Snapshot
	}
	return nil
}

type isSnapshotRequest_Request interface {
	isSnapshotRequest_Request()
}

type SnapshotRequest_Setup_ struct {
	Setup *SnapshotRequest_Setup `protobuf:"bytes,1,opt,name=setup,proto3,oneof"`
}

type SnapshotRequest_Snapshot_ struct {
	Snapshot *SnapshotRequest_Snapshot `protobuf:"bytes,2,opt,name=snapshot,proto3,oneof"`
}

func (*SnapshotRequest_Setup_) isSnapshotRequest_Request() {}

func (*SnapshotRequest_Snapshot_) isSnapshotRequest_Request() {}

type EventsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Request:
	//
	//	*EventsRequest_Setup_
	//	*EventsRequest_Stream_
	//	*EventsRequest_Finish_
	Request isEventsRequest_Request `protobuf_oneof:"request"`
}

func (x *EventsRequest) Reset() {
	*x = EventsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_machina_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EventsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventsRequest) ProtoMessage() {}

func (x *EventsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_machina_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventsRequest.ProtoReflect.Descriptor instead.
func (*EventsRequest) Descriptor() ([]byte, []int) {
	return file_machina_proto_rawDescGZIP(), []int{4}
}

func (m *EventsRequest) GetRequest() isEventsRequest_Request {
	if m != nil {
		return m.Request
	}
	return nil
}

func (x *EventsRequest) GetSetup() *EventsRequest_Setup {
	if x, ok := x.GetRequest().(*EventsRequest_Setup_); ok {
		return x.Setup
	}
	return nil
}

func (x *EventsRequest) GetStream() *EventsRequest_Stream {
	if x, ok := x.GetRequest().(*EventsRequest_Stream_); ok {
		return x.Stream
	}
	return nil
}

func (x *EventsRequest) GetFinish() *EventsRequest_Finish {
	if x, ok := x.GetRequest().(*EventsRequest_Finish_); ok {
		return x.Finish
	}
	return nil
}

type isEventsRequest_Request interface {
	isEventsRequest_Request()
}

type EventsRequest_Setup_ struct {
	Setup *EventsRequest_Setup `protobuf:"bytes,1,opt,name=setup,proto3,oneof"`
}

type EventsRequest_Stream_ struct {
	Stream *EventsRequest_Stream `protobuf:"bytes,2,opt,name=stream,proto3,oneof"`
}

type EventsRequest_Finish_ struct {
	Finish *EventsRequest_Finish `protobuf:"bytes,3,opt,name=finish,proto3,oneof"`
}

func (*EventsRequest_Setup_) isEventsRequest_Request() {}

func (*EventsRequest_Stream_) isEventsRequest_Request() {}

func (*EventsRequest_Finish_) isEventsRequest_Request() {}

// Corresponds to
// https://arrow.apache.org/rust/arrow_ipc/writer/struct.EncodedData.html
type ArrowEncodedData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IpcMessage []byte `protobuf:"bytes,1,opt,name=ipc_message,json=ipcMessage,proto3" json:"ipc_message,omitempty"`
	ArrowData  []byte `protobuf:"bytes,2,opt,name=arrow_data,json=arrowData,proto3" json:"arrow_data,omitempty"`
}

func (x *ArrowEncodedData) Reset() {
	*x = ArrowEncodedData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_machina_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ArrowEncodedData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArrowEncodedData) ProtoMessage() {}

func (x *ArrowEncodedData) ProtoReflect() protoreflect.Message {
	mi := &file_machina_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArrowEncodedData.ProtoReflect.Descriptor instead.
func (*ArrowEncodedData) Descriptor() ([]byte, []int) {
	return file_machina_proto_rawDescGZIP(), []int{5}
}

func (x *ArrowEncodedData) GetIpcMessage() []byte {
	if x != nil {
		return x.IpcMessage
	}
	return nil
}

func (x *ArrowEncodedData) GetArrowData() []byte {
	if x != nil {
		return x.ArrowData
	}
	return nil
}

type ArrowIpcMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Kind        ArrowIpcMessage_Kind `protobuf:"varint,2,opt,name=kind,proto3,enum=machina.ArrowIpcMessage_Kind" json:"kind,omitempty"`
	EncodedData *ArrowEncodedData    `protobuf:"bytes,3,opt,name=encoded_data,json=encodedData,proto3" json:"encoded_data,omitempty"`
}

func (x *ArrowIpcMessage) Reset() {
	*x = ArrowIpcMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_machina_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ArrowIpcMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArrowIpcMessage) ProtoMessage() {}

func (x *ArrowIpcMessage) ProtoReflect() protoreflect.Message {
	mi := &file_machina_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArrowIpcMessage.ProtoReflect.Descriptor instead.
func (*ArrowIpcMessage) Descriptor() ([]byte, []int) {
	return file_machina_proto_rawDescGZIP(), []int{6}
}

func (x *ArrowIpcMessage) GetKind() ArrowIpcMessage_Kind {
	if x != nil {
		return x.Kind
	}
	return ArrowIpcMessage_UNKNOWN
}

func (x *ArrowIpcMessage) GetEncodedData() *ArrowEncodedData {
	if x != nil {
		return x.EncodedData
	}
	return nil
}

type ArrowIpcStream struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Id of a physical arrow ipc stream. Logical meaning of the id is established
	// by ex and the provided wasm event processing program.
	Id       uint32             `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Messages []*ArrowIpcMessage `protobuf:"bytes,2,rep,name=messages,proto3" json:"messages,omitempty"`
}

func (x *ArrowIpcStream) Reset() {
	*x = ArrowIpcStream{}
	if protoimpl.UnsafeEnabled {
		mi := &file_machina_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ArrowIpcStream) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArrowIpcStream) ProtoMessage() {}

func (x *ArrowIpcStream) ProtoReflect() protoreflect.Message {
	mi := &file_machina_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArrowIpcStream.ProtoReflect.Descriptor instead.
func (*ArrowIpcStream) Descriptor() ([]byte, []int) {
	return file_machina_proto_rawDescGZIP(), []int{7}
}

func (x *ArrowIpcStream) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ArrowIpcStream) GetMessages() []*ArrowIpcMessage {
	if x != nil {
		return x.Messages
	}
	return nil
}

type ArrowIpcStreams struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Streams []*ArrowIpcStream `protobuf:"bytes,1,rep,name=streams,proto3" json:"streams,omitempty"`
}

func (x *ArrowIpcStreams) Reset() {
	*x = ArrowIpcStreams{}
	if protoimpl.UnsafeEnabled {
		mi := &file_machina_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ArrowIpcStreams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArrowIpcStreams) ProtoMessage() {}

func (x *ArrowIpcStreams) ProtoReflect() protoreflect.Message {
	mi := &file_machina_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArrowIpcStreams.ProtoReflect.Descriptor instead.
func (*ArrowIpcStreams) Descriptor() ([]byte, []int) {
	return file_machina_proto_rawDescGZIP(), []int{8}
}

func (x *ArrowIpcStreams) GetStreams() []*ArrowIpcStream {
	if x != nil {
		return x.Streams
	}
	return nil
}

type EventsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Response:
	//
	//	*EventsResponse_Event_
	//	*EventsResponse_ApproximateBootTime_
	//	*EventsResponse_Attached_
	//	*EventsResponse_Detached_
	//	*EventsResponse_ArrowStreams
	Response isEventsResponse_Response `protobuf_oneof:"response"`
}

func (x *EventsResponse) Reset() {
	*x = EventsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_machina_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EventsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventsResponse) ProtoMessage() {}

func (x *EventsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_machina_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventsResponse.ProtoReflect.Descriptor instead.
func (*EventsResponse) Descriptor() ([]byte, []int) {
	return file_machina_proto_rawDescGZIP(), []int{9}
}

func (m *EventsResponse) GetResponse() isEventsResponse_Response {
	if m != nil {
		return m.Response
	}
	return nil
}

func (x *EventsResponse) GetEvent() *EventsResponse_Event {
	if x, ok := x.GetResponse().(*EventsResponse_Event_); ok {
		return x.Event
	}
	return nil
}

func (x *EventsResponse) GetApproximateBootTime() *EventsResponse_ApproximateBootTime {
	if x, ok := x.GetResponse().(*EventsResponse_ApproximateBootTime_); ok {
		return x.ApproximateBootTime
	}
	return nil
}

func (x *EventsResponse) GetAttached() *EventsResponse_Attached {
	if x, ok := x.GetResponse().(*EventsResponse_Attached_); ok {
		return x.Attached
	}
	return nil
}

func (x *EventsResponse) GetDetached() *EventsResponse_Detached {
	if x, ok := x.GetResponse().(*EventsResponse_Detached_); ok {
		return x.Detached
	}
	return nil
}

func (x *EventsResponse) GetArrowStreams() *ArrowIpcStreams {
	if x, ok := x.GetResponse().(*EventsResponse_ArrowStreams); ok {
		return x.ArrowStreams
	}
	return nil
}

type isEventsResponse_Response interface {
	isEventsResponse_Response()
}

type EventsResponse_Event_ struct {
	Event *EventsResponse_Event `protobuf:"bytes,1,opt,name=event,proto3,oneof"`
}

type EventsResponse_ApproximateBootTime_ struct {
	ApproximateBootTime *EventsResponse_ApproximateBootTime `protobuf:"bytes,2,opt,name=approximate_boot_time,json=approximateBootTime,proto3,oneof"`
}

type EventsResponse_Attached_ struct {
	Attached *EventsResponse_Attached `protobuf:"bytes,3,opt,name=attached,proto3,oneof"`
}

type EventsResponse_Detached_ struct {
	Detached *EventsResponse_Detached `protobuf:"bytes,4,opt,name=detached,proto3,oneof"`
}

type EventsResponse_ArrowStreams struct {
	ArrowStreams *ArrowIpcStreams `protobuf:"bytes,5,opt,name=arrow_streams,json=arrowStreams,proto3,oneof"`
}

func (*EventsResponse_Event_) isEventsResponse_Response() {}

func (*EventsResponse_ApproximateBootTime_) isEventsResponse_Response() {}

func (*EventsResponse_Attached_) isEventsResponse_Response() {}

func (*EventsResponse_Detached_) isEventsResponse_Response() {}

func (*EventsResponse_ArrowStreams) isEventsResponse_Response() {}

type SnapshotResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data []byte `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	// The timestamp of the snapshot. This is a best-effort timestamp that
	// should closely match the time at which the snapshot was taken.
	Timestamp *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// The duration of the pause for the snapshot as observed by the agent.
	PauseDurationNs uint64 `protobuf:"varint,3,opt,name=pause_duration_ns,json=pauseDurationNs,proto3" json:"pause_duration_ns,omitempty"`
	// The approximate boot time of the process. This can
	// be used to translate the timestamps communicated in
	// clock_monotonic to human time.
	ApproximateBootTime *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=approximate_boot_time,json=approximateBootTime,proto3" json:"approximate_boot_time,omitempty"`
	// / The difference between actual virtual address in bss section and virtual
	// / address according to debug information, due to address space layout
	// / randomization (ASLR).
	BssAddrShift uint64 `protobuf:"varint,5,opt,name=bss_addr_shift,json=bssAddrShift,proto3" json:"bss_addr_shift,omitempty"`
}

func (x *SnapshotResponse) Reset() {
	*x = SnapshotResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_machina_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SnapshotResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SnapshotResponse) ProtoMessage() {}

func (x *SnapshotResponse) ProtoReflect() protoreflect.Message {
	mi := &file_machina_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SnapshotResponse.ProtoReflect.Descriptor instead.
func (*SnapshotResponse) Descriptor() ([]byte, []int) {
	return file_machina_proto_rawDescGZIP(), []int{10}
}

func (x *SnapshotResponse) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *SnapshotResponse) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *SnapshotResponse) GetPauseDurationNs() uint64 {
	if x != nil {
		return x.PauseDurationNs
	}
	return 0
}

func (x *SnapshotResponse) GetApproximateBootTime() *timestamppb.Timestamp {
	if x != nil {
		return x.ApproximateBootTime
	}
	return nil
}

func (x *SnapshotResponse) GetBssAddrShift() uint64 {
	if x != nil {
		return x.BssAddrShift
	}
	return 0
}

type MachinaInfoRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *MachinaInfoRequest) Reset() {
	*x = MachinaInfoRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_machina_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MachinaInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MachinaInfoRequest) ProtoMessage() {}

func (x *MachinaInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_machina_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MachinaInfoRequest.ProtoReflect.Descriptor instead.
func (*MachinaInfoRequest) Descriptor() ([]byte, []int) {
	return file_machina_proto_rawDescGZIP(), []int{11}
}

type MachinaInfoResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// A unique identifier for this machina.
	Fingerprint string `protobuf:"bytes,1,opt,name=fingerprint,proto3" json:"fingerprint,omitempty"`
	// The hostname of the machina.
	Hostname string `protobuf:"bytes,3,opt,name=hostname,proto3" json:"hostname,omitempty"`
	// The agent version.
	Version string `protobuf:"bytes,4,opt,name=version,proto3" json:"version,omitempty"`
	// The version of the kernel in "{major}.{minor}.{patch}" format.
	KernelVersion string `protobuf:"bytes,8,opt,name=kernel_version,json=kernelVersion,proto3" json:"kernel_version,omitempty"`
	// The token of the tenant to which this machina belongs.
	//
	// TODO: Define any structure for this token. For now it's opaque and will
	// correspond to the token used to scope requests to a tenant.
	TenantToken string `protobuf:"bytes,5,opt,name=tenant_token,json=tenantToken,proto3" json:"tenant_token,omitempty"`
	// The environment flag passed to the machina.
	Environment string `protobuf:"bytes,6,opt,name=environment,proto3" json:"environment,omitempty"`
	// The IP addresses of the machina.
	IpAddresses []string `protobuf:"bytes,7,rep,name=ip_addresses,json=ipAddresses,proto3" json:"ip_addresses,omitempty"`
	// is_library indicates that this agent is a library, monitoring its own
	// process.
	IsLibrary bool `protobuf:"varint,9,opt,name=is_library,json=isLibrary,proto3" json:"is_library,omitempty"`
}

func (x *MachinaInfoResponse) Reset() {
	*x = MachinaInfoResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_machina_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MachinaInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MachinaInfoResponse) ProtoMessage() {}

func (x *MachinaInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_machina_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MachinaInfoResponse.ProtoReflect.Descriptor instead.
func (*MachinaInfoResponse) Descriptor() ([]byte, []int) {
	return file_machina_proto_rawDescGZIP(), []int{12}
}

func (x *MachinaInfoResponse) GetFingerprint() string {
	if x != nil {
		return x.Fingerprint
	}
	return ""
}

func (x *MachinaInfoResponse) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *MachinaInfoResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *MachinaInfoResponse) GetKernelVersion() string {
	if x != nil {
		return x.KernelVersion
	}
	return ""
}

func (x *MachinaInfoResponse) GetTenantToken() string {
	if x != nil {
		return x.TenantToken
	}
	return ""
}

func (x *MachinaInfoResponse) GetEnvironment() string {
	if x != nil {
		return x.Environment
	}
	return ""
}

func (x *MachinaInfoResponse) GetIpAddresses() []string {
	if x != nil {
		return x.IpAddresses
	}
	return nil
}

func (x *MachinaInfoResponse) GetIsLibrary() bool {
	if x != nil {
		return x.IsLibrary
	}
	return false
}

// Setup is the first message from the client in the Snapshot protocol.
type SnapshotRequest_Setup struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The key associated with the artifacts needed for this snapshot.
	Key string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	// The fingerprint of the process to snapshot.
	ProcessFingerprint string `protobuf:"bytes,2,opt,name=process_fingerprint,json=processFingerprint,proto3" json:"process_fingerprint,omitempty"`
}

func (x *SnapshotRequest_Setup) Reset() {
	*x = SnapshotRequest_Setup{}
	if protoimpl.UnsafeEnabled {
		mi := &file_machina_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SnapshotRequest_Setup) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SnapshotRequest_Setup) ProtoMessage() {}

func (x *SnapshotRequest_Setup) ProtoReflect() protoreflect.Message {
	mi := &file_machina_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SnapshotRequest_Setup.ProtoReflect.Descriptor instead.
func (*SnapshotRequest_Setup) Descriptor() ([]byte, []int) {
	return file_machina_proto_rawDescGZIP(), []int{3, 0}
}

func (x *SnapshotRequest_Setup) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *SnapshotRequest_Setup) GetProcessFingerprint() string {
	if x != nil {
		return x.ProcessFingerprint
	}
	return ""
}

// Snapshot is the second message from the client in the Snapshot protocol.
// It trggers the snapshot process.
type SnapshotRequest_Snapshot struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *SnapshotRequest_Snapshot) Reset() {
	*x = SnapshotRequest_Snapshot{}
	if protoimpl.UnsafeEnabled {
		mi := &file_machina_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SnapshotRequest_Snapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SnapshotRequest_Snapshot) ProtoMessage() {}

func (x *SnapshotRequest_Snapshot) ProtoReflect() protoreflect.Message {
	mi := &file_machina_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SnapshotRequest_Snapshot.ProtoReflect.Descriptor instead.
func (*SnapshotRequest_Snapshot) Descriptor() ([]byte, []int) {
	return file_machina_proto_rawDescGZIP(), []int{3, 1}
}

type EventsRequest_Setup struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The key associated with the artifacts needed for this snapshot.
	Key string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	// The fingerprint of the process to probe.
	ProcessFingerprint string `protobuf:"bytes,2,opt,name=process_fingerprint,json=processFingerprint,proto3" json:"process_fingerprint,omitempty"`
}

func (x *EventsRequest_Setup) Reset() {
	*x = EventsRequest_Setup{}
	if protoimpl.UnsafeEnabled {
		mi := &file_machina_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EventsRequest_Setup) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventsRequest_Setup) ProtoMessage() {}

func (x *EventsRequest_Setup) ProtoReflect() protoreflect.Message {
	mi := &file_machina_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventsRequest_Setup.ProtoReflect.Descriptor instead.
func (*EventsRequest_Setup) Descriptor() ([]byte, []int) {
	return file_machina_proto_rawDescGZIP(), []int{4, 0}
}

func (x *EventsRequest_Setup) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *EventsRequest_Setup) GetProcessFingerprint() string {
	if x != nil {
		return x.ProcessFingerprint
	}
	return ""
}

type EventsRequest_Stream struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The number of events to stream.
	MaxCount uint32 `protobuf:"varint,1,opt,name=max_count,json=maxCount,proto3" json:"max_count,omitempty"`
	// The duration to stream events for. This is used as an upper bound on the
	// duration to run the probe. In the common case, the client should send a
	// finish message to terminate the probe before this duration elapses. This
	// value is used to defend against unresponsive clients.
	DurationNs *uint64 `protobuf:"varint,2,opt,name=duration_ns,json=durationNs,proto3,oneof" json:"duration_ns,omitempty"`
}

func (x *EventsRequest_Stream) Reset() {
	*x = EventsRequest_Stream{}
	if protoimpl.UnsafeEnabled {
		mi := &file_machina_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EventsRequest_Stream) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventsRequest_Stream) ProtoMessage() {}

func (x *EventsRequest_Stream) ProtoReflect() protoreflect.Message {
	mi := &file_machina_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventsRequest_Stream.ProtoReflect.Descriptor instead.
func (*EventsRequest_Stream) Descriptor() ([]byte, []int) {
	return file_machina_proto_rawDescGZIP(), []int{4, 1}
}

func (x *EventsRequest_Stream) GetMaxCount() uint32 {
	if x != nil {
		return x.MaxCount
	}
	return 0
}

func (x *EventsRequest_Stream) GetDurationNs() uint64 {
	if x != nil && x.DurationNs != nil {
		return *x.DurationNs
	}
	return 0
}

type EventsRequest_Finish struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *EventsRequest_Finish) Reset() {
	*x = EventsRequest_Finish{}
	if protoimpl.UnsafeEnabled {
		mi := &file_machina_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EventsRequest_Finish) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventsRequest_Finish) ProtoMessage() {}

func (x *EventsRequest_Finish) ProtoReflect() protoreflect.Message {
	mi := &file_machina_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventsRequest_Finish.ProtoReflect.Descriptor instead.
func (*EventsRequest_Finish) Descriptor() ([]byte, []int) {
	return file_machina_proto_rawDescGZIP(), []int{4, 2}
}

type EventsResponse_Event struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data []byte `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *EventsResponse_Event) Reset() {
	*x = EventsResponse_Event{}
	if protoimpl.UnsafeEnabled {
		mi := &file_machina_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EventsResponse_Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventsResponse_Event) ProtoMessage() {}

func (x *EventsResponse_Event) ProtoReflect() protoreflect.Message {
	mi := &file_machina_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventsResponse_Event.ProtoReflect.Descriptor instead.
func (*EventsResponse_Event) Descriptor() ([]byte, []int) {
	return file_machina_proto_rawDescGZIP(), []int{9, 0}
}

func (x *EventsResponse_Event) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

// ApproximateBootTime is sent after the probes have been loaded.
// It is needed because bpf only has access to CLOCK_MONOTONIC time
// (at least until version 6.1 when bpf_ktime_get_tai_ns was introduced).
// This value is used to adjust the timestamp in the event to a wall clock
// timestamp. It will be approximate, but should be close enough.
type EventsResponse_ApproximateBootTime struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ApproximateBootTimeNs uint64 `protobuf:"varint,1,opt,name=approximate_boot_time_ns,json=approximateBootTimeNs,proto3" json:"approximate_boot_time_ns,omitempty"`
}

func (x *EventsResponse_ApproximateBootTime) Reset() {
	*x = EventsResponse_ApproximateBootTime{}
	if protoimpl.UnsafeEnabled {
		mi := &file_machina_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EventsResponse_ApproximateBootTime) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventsResponse_ApproximateBootTime) ProtoMessage() {}

func (x *EventsResponse_ApproximateBootTime) ProtoReflect() protoreflect.Message {
	mi := &file_machina_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventsResponse_ApproximateBootTime.ProtoReflect.Descriptor instead.
func (*EventsResponse_ApproximateBootTime) Descriptor() ([]byte, []int) {
	return file_machina_proto_rawDescGZIP(), []int{9, 1}
}

func (x *EventsResponse_ApproximateBootTime) GetApproximateBootTimeNs() uint64 {
	if x != nil {
		return x.ApproximateBootTimeNs
	}
	return 0
}

type EventsResponse_Attached struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// A timestamp that precedes the first event.
	AttachedTimestampMonotonicNs uint64 `protobuf:"varint,1,opt,name=attached_timestamp_monotonic_ns,json=attachedTimestampMonotonicNs,proto3" json:"attached_timestamp_monotonic_ns,omitempty"`
}

func (x *EventsResponse_Attached) Reset() {
	*x = EventsResponse_Attached{}
	if protoimpl.UnsafeEnabled {
		mi := &file_machina_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EventsResponse_Attached) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventsResponse_Attached) ProtoMessage() {}

func (x *EventsResponse_Attached) ProtoReflect() protoreflect.Message {
	mi := &file_machina_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventsResponse_Attached.ProtoReflect.Descriptor instead.
func (*EventsResponse_Attached) Descriptor() ([]byte, []int) {
	return file_machina_proto_rawDescGZIP(), []int{9, 2}
}

func (x *EventsResponse_Attached) GetAttachedTimestampMonotonicNs() uint64 {
	if x != nil {
		return x.AttachedTimestampMonotonicNs
	}
	return 0
}

type EventsResponse_SummaryStatistics struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	EventsDroppedInEbpf  uint32 `protobuf:"varint,2,opt,name=events_dropped_in_ebpf,json=eventsDroppedInEbpf,proto3" json:"events_dropped_in_ebpf,omitempty"`
	EventsRejectedInEbpf uint32 `protobuf:"varint,3,opt,name=events_rejected_in_ebpf,json=eventsRejectedInEbpf,proto3" json:"events_rejected_in_ebpf,omitempty"`
}

func (x *EventsResponse_SummaryStatistics) Reset() {
	*x = EventsResponse_SummaryStatistics{}
	if protoimpl.UnsafeEnabled {
		mi := &file_machina_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EventsResponse_SummaryStatistics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventsResponse_SummaryStatistics) ProtoMessage() {}

func (x *EventsResponse_SummaryStatistics) ProtoReflect() protoreflect.Message {
	mi := &file_machina_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventsResponse_SummaryStatistics.ProtoReflect.Descriptor instead.
func (*EventsResponse_SummaryStatistics) Descriptor() ([]byte, []int) {
	return file_machina_proto_rawDescGZIP(), []int{9, 3}
}

func (x *EventsResponse_SummaryStatistics) GetEventsDroppedInEbpf() uint32 {
	if x != nil {
		return x.EventsDroppedInEbpf
	}
	return 0
}

func (x *EventsResponse_SummaryStatistics) GetEventsRejectedInEbpf() uint32 {
	if x != nil {
		return x.EventsRejectedInEbpf
	}
	return 0
}

type EventsResponse_Detached struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SummaryStatistics *EventsResponse_SummaryStatistics `protobuf:"bytes,1,opt,name=summary_statistics,json=summaryStatistics,proto3" json:"summary_statistics,omitempty"`
	// The timestamp of the detached event.
	DetachedTimestampMonotonicNs uint64 `protobuf:"varint,2,opt,name=detached_timestamp_monotonic_ns,json=detachedTimestampMonotonicNs,proto3" json:"detached_timestamp_monotonic_ns,omitempty"`
}

func (x *EventsResponse_Detached) Reset() {
	*x = EventsResponse_Detached{}
	if protoimpl.UnsafeEnabled {
		mi := &file_machina_proto_msgTypes[22]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EventsResponse_Detached) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventsResponse_Detached) ProtoMessage() {}

func (x *EventsResponse_Detached) ProtoReflect() protoreflect.Message {
	mi := &file_machina_proto_msgTypes[22]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventsResponse_Detached.ProtoReflect.Descriptor instead.
func (*EventsResponse_Detached) Descriptor() ([]byte, []int) {
	return file_machina_proto_rawDescGZIP(), []int{9, 4}
}

func (x *EventsResponse_Detached) GetSummaryStatistics() *EventsResponse_SummaryStatistics {
	if x != nil {
		return x.SummaryStatistics
	}
	return nil
}

func (x *EventsResponse_Detached) GetDetachedTimestampMonotonicNs() uint64 {
	if x != nil {
		return x.DetachedTimestampMonotonicNs
	}
	return 0
}

var File_machina_proto protoreflect.FileDescriptor

var file_machina_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x6d, 0x61, 0x63, 0x68, 0x69, 0x6e, 0x61, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x07, 0x6d, 0x61, 0x63, 0x68, 0x69, 0x6e, 0x61, 0x1a, 0x0d, 0x70, 0x72, 0x6f, 0x63, 0x65, 0x73,
	0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x0b, 0x63, 0x68, 0x75, 0x6e, 0x6b, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x52, 0x0a, 0x15, 0x57, 0x61, 0x74, 0x63, 0x68, 0x50, 0x72,
	0x6f, 0x63, 0x65, 0x73, 0x73, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x33,
	0x0a, 0x0b, 0x6c, 0x61, 0x62, 0x65, 0x6c, 0x5f, 0x72, 0x75, 0x6c, 0x65, 0x73, 0x18, 0x02, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x70, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x2e, 0x4c, 0x61,
	0x62, 0x65, 0x6c, 0x52, 0x75, 0x6c, 0x65, 0x52, 0x0a, 0x6c, 0x61, 0x62, 0x65, 0x6c, 0x52, 0x75,
	0x6c, 0x65, 0x73, 0x4a, 0x04, 0x08, 0x01, 0x10, 0x02, 0x22, 0x6a, 0x0a, 0x06, 0x55, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x12, 0x26, 0x0a, 0x05, 0x61, 0x64, 0x64, 0x65, 0x64, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x10, 0x2e, 0x70, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x2e, 0x50, 0x72, 0x6f,
	0x63, 0x65, 0x73, 0x73, 0x52, 0x05, 0x61, 0x64, 0x64, 0x65, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x72,
	0x65, 0x6d, 0x6f, 0x76, 0x65, 0x64, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x07, 0x72, 0x65,
	0x6d, 0x6f, 0x76, 0x65, 0x64, 0x12, 0x1e, 0x0a, 0x0a, 0x69, 0x6e, 0x63, 0x6f, 0x6d, 0x70, 0x6c,
	0x65, 0x74, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0a, 0x69, 0x6e, 0x63, 0x6f, 0x6d,
	0x70, 0x6c, 0x65, 0x74, 0x65, 0x22, 0x2a, 0x0a, 0x14, 0x47, 0x65, 0x74, 0x45, 0x78, 0x65, 0x63,
	0x75, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a,
	0x04, 0x68, 0x61, 0x73, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x68, 0x61, 0x73,
	0x68, 0x22, 0xed, 0x01, 0x0a, 0x0f, 0x53, 0x6e, 0x61, 0x70, 0x73, 0x68, 0x6f, 0x74, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x36, 0x0a, 0x05, 0x73, 0x65, 0x74, 0x75, 0x70, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x6d, 0x61, 0x63, 0x68, 0x69, 0x6e, 0x61, 0x2e, 0x53,
	0x6e, 0x61, 0x70, 0x73, 0x68, 0x6f, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x53,
	0x65, 0x74, 0x75, 0x70, 0x48, 0x00, 0x52, 0x05, 0x73, 0x65, 0x74, 0x75, 0x70, 0x12, 0x3f, 0x0a,
	0x08, 0x73, 0x6e, 0x61, 0x70, 0x73, 0x68, 0x6f, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x21, 0x2e, 0x6d, 0x61, 0x63, 0x68, 0x69, 0x6e, 0x61, 0x2e, 0x53, 0x6e, 0x61, 0x70, 0x73, 0x68,
	0x6f, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x53, 0x6e, 0x61, 0x70, 0x73, 0x68,
	0x6f, 0x74, 0x48, 0x00, 0x52, 0x08, 0x73, 0x6e, 0x61, 0x70, 0x73, 0x68, 0x6f, 0x74, 0x1a, 0x4a,
	0x0a, 0x05, 0x53, 0x65, 0x74, 0x75, 0x70, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x2f, 0x0a, 0x13, 0x70, 0x72, 0x6f,
	0x63, 0x65, 0x73, 0x73, 0x5f, 0x66, 0x69, 0x6e, 0x67, 0x65, 0x72, 0x70, 0x72, 0x69, 0x6e, 0x74,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x12, 0x70, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x46,
	0x69, 0x6e, 0x67, 0x65, 0x72, 0x70, 0x72, 0x69, 0x6e, 0x74, 0x1a, 0x0a, 0x0a, 0x08, 0x53, 0x6e,
	0x61, 0x70, 0x73, 0x68, 0x6f, 0x74, 0x42, 0x09, 0x0a, 0x07, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x22, 0xf5, 0x02, 0x0a, 0x0d, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x34, 0x0a, 0x05, 0x73, 0x65, 0x74, 0x75, 0x70, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x6d, 0x61, 0x63, 0x68, 0x69, 0x6e, 0x61, 0x2e, 0x45, 0x76, 0x65,
	0x6e, 0x74, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x53, 0x65, 0x74, 0x75, 0x70,
	0x48, 0x00, 0x52, 0x05, 0x73, 0x65, 0x74, 0x75, 0x70, 0x12, 0x37, 0x0a, 0x06, 0x73, 0x74, 0x72,
	0x65, 0x61, 0x6d, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x6d, 0x61, 0x63, 0x68,
	0x69, 0x6e, 0x61, 0x2e, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x2e, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x48, 0x00, 0x52, 0x06, 0x73, 0x74, 0x72, 0x65,
	0x61, 0x6d, 0x12, 0x37, 0x0a, 0x06, 0x66, 0x69, 0x6e, 0x69, 0x73, 0x68, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x6d, 0x61, 0x63, 0x68, 0x69, 0x6e, 0x61, 0x2e, 0x45, 0x76, 0x65,
	0x6e, 0x74, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x46, 0x69, 0x6e, 0x69, 0x73,
	0x68, 0x48, 0x00, 0x52, 0x06, 0x66, 0x69, 0x6e, 0x69, 0x73, 0x68, 0x1a, 0x4a, 0x0a, 0x05, 0x53,
	0x65, 0x74, 0x75, 0x70, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x2f, 0x0a, 0x13, 0x70, 0x72, 0x6f, 0x63, 0x65, 0x73,
	0x73, 0x5f, 0x66, 0x69, 0x6e, 0x67, 0x65, 0x72, 0x70, 0x72, 0x69, 0x6e, 0x74, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x12, 0x70, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x46, 0x69, 0x6e, 0x67,
	0x65, 0x72, 0x70, 0x72, 0x69, 0x6e, 0x74, 0x1a, 0x5b, 0x0a, 0x06, 0x53, 0x74, 0x72, 0x65, 0x61,
	0x6d, 0x12, 0x1b, 0x0a, 0x09, 0x6d, 0x61, 0x78, 0x5f, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0d, 0x52, 0x08, 0x6d, 0x61, 0x78, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x24,
	0x0a, 0x0b, 0x64, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x6e, 0x73, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x04, 0x48, 0x00, 0x52, 0x0a, 0x64, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4e,
	0x73, 0x88, 0x01, 0x01, 0x42, 0x0e, 0x0a, 0x0c, 0x5f, 0x64, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x5f, 0x6e, 0x73, 0x1a, 0x08, 0x0a, 0x06, 0x46, 0x69, 0x6e, 0x69, 0x73, 0x68, 0x42, 0x09,
	0x0a, 0x07, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x52, 0x0a, 0x10, 0x41, 0x72, 0x72,
	0x6f, 0x77, 0x45, 0x6e, 0x63, 0x6f, 0x64, 0x65, 0x64, 0x44, 0x61, 0x74, 0x61, 0x12, 0x1f, 0x0a,
	0x0b, 0x69, 0x70, 0x63, 0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0c, 0x52, 0x0a, 0x69, 0x70, 0x63, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x1d,
	0x0a, 0x0a, 0x61, 0x72, 0x72, 0x6f, 0x77, 0x5f, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0c, 0x52, 0x09, 0x61, 0x72, 0x72, 0x6f, 0x77, 0x44, 0x61, 0x74, 0x61, 0x22, 0xe3, 0x01,
	0x0a, 0x0f, 0x41, 0x72, 0x72, 0x6f, 0x77, 0x49, 0x70, 0x63, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x12, 0x31, 0x0a, 0x04, 0x6b, 0x69, 0x6e, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32,
	0x1d, 0x2e, 0x6d, 0x61, 0x63, 0x68, 0x69, 0x6e, 0x61, 0x2e, 0x41, 0x72, 0x72, 0x6f, 0x77, 0x49,
	0x70, 0x63, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x4b, 0x69, 0x6e, 0x64, 0x52, 0x04,
	0x6b, 0x69, 0x6e, 0x64, 0x12, 0x3c, 0x0a, 0x0c, 0x65, 0x6e, 0x63, 0x6f, 0x64, 0x65, 0x64, 0x5f,
	0x64, 0x61, 0x74, 0x61, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x6d, 0x61, 0x63,
	0x68, 0x69, 0x6e, 0x61, 0x2e, 0x41, 0x72, 0x72, 0x6f, 0x77, 0x45, 0x6e, 0x63, 0x6f, 0x64, 0x65,
	0x64, 0x44, 0x61, 0x74, 0x61, 0x52, 0x0b, 0x65, 0x6e, 0x63, 0x6f, 0x64, 0x65, 0x64, 0x44, 0x61,
	0x74, 0x61, 0x22, 0x5f, 0x0a, 0x04, 0x4b, 0x69, 0x6e, 0x64, 0x12, 0x0b, 0x0a, 0x07, 0x55, 0x4e,
	0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x10, 0x00, 0x12, 0x22, 0x0a, 0x1e, 0x53, 0x43, 0x48, 0x45, 0x4d,
	0x41, 0x5f, 0x57, 0x49, 0x54, 0x48, 0x5f, 0x44, 0x49, 0x43, 0x54, 0x49, 0x4f, 0x4e, 0x41, 0x52,
	0x59, 0x5f, 0x54, 0x52, 0x41, 0x43, 0x4b, 0x45, 0x52, 0x10, 0x01, 0x12, 0x14, 0x0a, 0x10, 0x44,
	0x49, 0x43, 0x54, 0x49, 0x4f, 0x4e, 0x41, 0x52, 0x59, 0x5f, 0x42, 0x41, 0x54, 0x43, 0x48, 0x10,
	0x02, 0x12, 0x10, 0x0a, 0x0c, 0x52, 0x45, 0x43, 0x4f, 0x52, 0x44, 0x5f, 0x42, 0x41, 0x54, 0x43,
	0x48, 0x10, 0x03, 0x22, 0x56, 0x0a, 0x0e, 0x41, 0x72, 0x72, 0x6f, 0x77, 0x49, 0x70, 0x63, 0x53,
	0x74, 0x72, 0x65, 0x61, 0x6d, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0d, 0x52, 0x02, 0x69, 0x64, 0x12, 0x34, 0x0a, 0x08, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x6d, 0x61, 0x63, 0x68, 0x69, 0x6e,
	0x61, 0x2e, 0x41, 0x72, 0x72, 0x6f, 0x77, 0x49, 0x70, 0x63, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x52, 0x08, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x22, 0x44, 0x0a, 0x0f, 0x41,
	0x72, 0x72, 0x6f, 0x77, 0x49, 0x70, 0x63, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x73, 0x12, 0x31,
	0x0a, 0x07, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x17, 0x2e, 0x6d, 0x61, 0x63, 0x68, 0x69, 0x6e, 0x61, 0x2e, 0x41, 0x72, 0x72, 0x6f, 0x77, 0x49,
	0x70, 0x63, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x52, 0x07, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d,
	0x73, 0x22, 0xed, 0x06, 0x0a, 0x0e, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x35, 0x0a, 0x05, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x6d, 0x61, 0x63, 0x68, 0x69, 0x6e, 0x61, 0x2e, 0x45, 0x76,
	0x65, 0x6e, 0x74, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x45, 0x76, 0x65,
	0x6e, 0x74, 0x48, 0x00, 0x52, 0x05, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x12, 0x61, 0x0a, 0x15, 0x61,
	0x70, 0x70, 0x72, 0x6f, 0x78, 0x69, 0x6d, 0x61, 0x74, 0x65, 0x5f, 0x62, 0x6f, 0x6f, 0x74, 0x5f,
	0x74, 0x69, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x2b, 0x2e, 0x6d, 0x61, 0x63,
	0x68, 0x69, 0x6e, 0x61, 0x2e, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x2e, 0x41, 0x70, 0x70, 0x72, 0x6f, 0x78, 0x69, 0x6d, 0x61, 0x74, 0x65, 0x42,
	0x6f, 0x6f, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x48, 0x00, 0x52, 0x13, 0x61, 0x70, 0x70, 0x72, 0x6f,
	0x78, 0x69, 0x6d, 0x61, 0x74, 0x65, 0x42, 0x6f, 0x6f, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x3e,
	0x0a, 0x08, 0x61, 0x74, 0x74, 0x61, 0x63, 0x68, 0x65, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x20, 0x2e, 0x6d, 0x61, 0x63, 0x68, 0x69, 0x6e, 0x61, 0x2e, 0x45, 0x76, 0x65, 0x6e, 0x74,
	0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x41, 0x74, 0x74, 0x61, 0x63, 0x68,
	0x65, 0x64, 0x48, 0x00, 0x52, 0x08, 0x61, 0x74, 0x74, 0x61, 0x63, 0x68, 0x65, 0x64, 0x12, 0x3e,
	0x0a, 0x08, 0x64, 0x65, 0x74, 0x61, 0x63, 0x68, 0x65, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x20, 0x2e, 0x6d, 0x61, 0x63, 0x68, 0x69, 0x6e, 0x61, 0x2e, 0x45, 0x76, 0x65, 0x6e, 0x74,
	0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x44, 0x65, 0x74, 0x61, 0x63, 0x68,
	0x65, 0x64, 0x48, 0x00, 0x52, 0x08, 0x64, 0x65, 0x74, 0x61, 0x63, 0x68, 0x65, 0x64, 0x12, 0x3f,
	0x0a, 0x0d, 0x61, 0x72, 0x72, 0x6f, 0x77, 0x5f, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x73, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x6d, 0x61, 0x63, 0x68, 0x69, 0x6e, 0x61, 0x2e,
	0x41, 0x72, 0x72, 0x6f, 0x77, 0x49, 0x70, 0x63, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x73, 0x48,
	0x00, 0x52, 0x0c, 0x61, 0x72, 0x72, 0x6f, 0x77, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x73, 0x1a,
	0x1b, 0x0a, 0x05, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x1a, 0x4e, 0x0a, 0x13,
	0x41, 0x70, 0x70, 0x72, 0x6f, 0x78, 0x69, 0x6d, 0x61, 0x74, 0x65, 0x42, 0x6f, 0x6f, 0x74, 0x54,
	0x69, 0x6d, 0x65, 0x12, 0x37, 0x0a, 0x18, 0x61, 0x70, 0x70, 0x72, 0x6f, 0x78, 0x69, 0x6d, 0x61,
	0x74, 0x65, 0x5f, 0x62, 0x6f, 0x6f, 0x74, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x5f, 0x6e, 0x73, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x15, 0x61, 0x70, 0x70, 0x72, 0x6f, 0x78, 0x69, 0x6d, 0x61,
	0x74, 0x65, 0x42, 0x6f, 0x6f, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x4e, 0x73, 0x1a, 0x51, 0x0a, 0x08,
	0x41, 0x74, 0x74, 0x61, 0x63, 0x68, 0x65, 0x64, 0x12, 0x45, 0x0a, 0x1f, 0x61, 0x74, 0x74, 0x61,
	0x63, 0x68, 0x65, 0x64, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x5f, 0x6d,
	0x6f, 0x6e, 0x6f, 0x74, 0x6f, 0x6e, 0x69, 0x63, 0x5f, 0x6e, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x04, 0x52, 0x1c, 0x61, 0x74, 0x74, 0x61, 0x63, 0x68, 0x65, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x73,
	0x74, 0x61, 0x6d, 0x70, 0x4d, 0x6f, 0x6e, 0x6f, 0x74, 0x6f, 0x6e, 0x69, 0x63, 0x4e, 0x73, 0x1a,
	0x85, 0x01, 0x0a, 0x11, 0x53, 0x75, 0x6d, 0x6d, 0x61, 0x72, 0x79, 0x53, 0x74, 0x61, 0x74, 0x69,
	0x73, 0x74, 0x69, 0x63, 0x73, 0x12, 0x33, 0x0a, 0x16, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x5f,
	0x64, 0x72, 0x6f, 0x70, 0x70, 0x65, 0x64, 0x5f, 0x69, 0x6e, 0x5f, 0x65, 0x62, 0x70, 0x66, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x13, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x44, 0x72, 0x6f,
	0x70, 0x70, 0x65, 0x64, 0x49, 0x6e, 0x45, 0x62, 0x70, 0x66, 0x12, 0x35, 0x0a, 0x17, 0x65, 0x76,
	0x65, 0x6e, 0x74, 0x73, 0x5f, 0x72, 0x65, 0x6a, 0x65, 0x63, 0x74, 0x65, 0x64, 0x5f, 0x69, 0x6e,
	0x5f, 0x65, 0x62, 0x70, 0x66, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x14, 0x65, 0x76, 0x65,
	0x6e, 0x74, 0x73, 0x52, 0x65, 0x6a, 0x65, 0x63, 0x74, 0x65, 0x64, 0x49, 0x6e, 0x45, 0x62, 0x70,
	0x66, 0x4a, 0x04, 0x08, 0x01, 0x10, 0x02, 0x1a, 0xab, 0x01, 0x0a, 0x08, 0x44, 0x65, 0x74, 0x61,
	0x63, 0x68, 0x65, 0x64, 0x12, 0x58, 0x0a, 0x12, 0x73, 0x75, 0x6d, 0x6d, 0x61, 0x72, 0x79, 0x5f,
	0x73, 0x74, 0x61, 0x74, 0x69, 0x73, 0x74, 0x69, 0x63, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x29, 0x2e, 0x6d, 0x61, 0x63, 0x68, 0x69, 0x6e, 0x61, 0x2e, 0x45, 0x76, 0x65, 0x6e, 0x74,
	0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x53, 0x75, 0x6d, 0x6d, 0x61, 0x72,
	0x79, 0x53, 0x74, 0x61, 0x74, 0x69, 0x73, 0x74, 0x69, 0x63, 0x73, 0x52, 0x11, 0x73, 0x75, 0x6d,
	0x6d, 0x61, 0x72, 0x79, 0x53, 0x74, 0x61, 0x74, 0x69, 0x73, 0x74, 0x69, 0x63, 0x73, 0x12, 0x45,
	0x0a, 0x1f, 0x64, 0x65, 0x74, 0x61, 0x63, 0x68, 0x65, 0x64, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x73,
	0x74, 0x61, 0x6d, 0x70, 0x5f, 0x6d, 0x6f, 0x6e, 0x6f, 0x74, 0x6f, 0x6e, 0x69, 0x63, 0x5f, 0x6e,
	0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x1c, 0x64, 0x65, 0x74, 0x61, 0x63, 0x68, 0x65,
	0x64, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x4d, 0x6f, 0x6e, 0x6f, 0x74, 0x6f,
	0x6e, 0x69, 0x63, 0x4e, 0x73, 0x42, 0x0a, 0x0a, 0x08, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x22, 0x82, 0x02, 0x0a, 0x10, 0x53, 0x6e, 0x61, 0x70, 0x73, 0x68, 0x6f, 0x74, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x12, 0x38, 0x0a, 0x09, 0x74, 0x69,
	0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e,
	0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e,
	0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73,
	0x74, 0x61, 0x6d, 0x70, 0x12, 0x2a, 0x0a, 0x11, 0x70, 0x61, 0x75, 0x73, 0x65, 0x5f, 0x64, 0x75,
	0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x6e, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x04, 0x52,
	0x0f, 0x70, 0x61, 0x75, 0x73, 0x65, 0x44, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4e, 0x73,
	0x12, 0x4e, 0x0a, 0x15, 0x61, 0x70, 0x70, 0x72, 0x6f, 0x78, 0x69, 0x6d, 0x61, 0x74, 0x65, 0x5f,
	0x62, 0x6f, 0x6f, 0x74, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x13, 0x61, 0x70, 0x70,
	0x72, 0x6f, 0x78, 0x69, 0x6d, 0x61, 0x74, 0x65, 0x42, 0x6f, 0x6f, 0x74, 0x54, 0x69, 0x6d, 0x65,
	0x12, 0x24, 0x0a, 0x0e, 0x62, 0x73, 0x73, 0x5f, 0x61, 0x64, 0x64, 0x72, 0x5f, 0x73, 0x68, 0x69,
	0x66, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0c, 0x62, 0x73, 0x73, 0x41, 0x64, 0x64,
	0x72, 0x53, 0x68, 0x69, 0x66, 0x74, 0x22, 0x14, 0x0a, 0x12, 0x4d, 0x61, 0x63, 0x68, 0x69, 0x6e,
	0x61, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x9b, 0x02, 0x0a,
	0x13, 0x4d, 0x61, 0x63, 0x68, 0x69, 0x6e, 0x61, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x66, 0x69, 0x6e, 0x67, 0x65, 0x72, 0x70, 0x72,
	0x69, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x66, 0x69, 0x6e, 0x67, 0x65,
	0x72, 0x70, 0x72, 0x69, 0x6e, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x68, 0x6f, 0x73, 0x74, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x68, 0x6f, 0x73, 0x74, 0x6e, 0x61,
	0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x25, 0x0a, 0x0e,
	0x6b, 0x65, 0x72, 0x6e, 0x65, 0x6c, 0x5f, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x08,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x6b, 0x65, 0x72, 0x6e, 0x65, 0x6c, 0x56, 0x65, 0x72, 0x73,
	0x69, 0x6f, 0x6e, 0x12, 0x21, 0x0a, 0x0c, 0x74, 0x65, 0x6e, 0x61, 0x6e, 0x74, 0x5f, 0x74, 0x6f,
	0x6b, 0x65, 0x6e, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x74, 0x65, 0x6e, 0x61, 0x6e,
	0x74, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x20, 0x0a, 0x0b, 0x65, 0x6e, 0x76, 0x69, 0x72, 0x6f,
	0x6e, 0x6d, 0x65, 0x6e, 0x74, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x65, 0x6e, 0x76,
	0x69, 0x72, 0x6f, 0x6e, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x21, 0x0a, 0x0c, 0x69, 0x70, 0x5f, 0x61,
	0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x65, 0x73, 0x18, 0x07, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0b,
	0x69, 0x70, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x65, 0x73, 0x12, 0x1d, 0x0a, 0x0a, 0x69,
	0x73, 0x5f, 0x6c, 0x69, 0x62, 0x72, 0x61, 0x72, 0x79, 0x18, 0x09, 0x20, 0x01, 0x28, 0x08, 0x52,
	0x09, 0x69, 0x73, 0x4c, 0x69, 0x62, 0x72, 0x61, 0x72, 0x79, 0x32, 0xe8, 0x02, 0x0a, 0x07, 0x4d,
	0x61, 0x63, 0x68, 0x69, 0x6e, 0x61, 0x12, 0x45, 0x0a, 0x0e, 0x57, 0x61, 0x74, 0x63, 0x68, 0x50,
	0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x65, 0x73, 0x12, 0x1e, 0x2e, 0x6d, 0x61, 0x63, 0x68, 0x69,
	0x6e, 0x61, 0x2e, 0x57, 0x61, 0x74, 0x63, 0x68, 0x50, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x65,
	0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x0f, 0x2e, 0x6d, 0x61, 0x63, 0x68, 0x69,
	0x6e, 0x61, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x22, 0x00, 0x30, 0x01, 0x12, 0x40, 0x0a,
	0x0d, 0x47, 0x65, 0x74, 0x45, 0x78, 0x65, 0x63, 0x75, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x12, 0x1d,
	0x2e, 0x6d, 0x61, 0x63, 0x68, 0x69, 0x6e, 0x61, 0x2e, 0x47, 0x65, 0x74, 0x45, 0x78, 0x65, 0x63,
	0x75, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x0c, 0x2e,
	0x63, 0x68, 0x75, 0x6e, 0x6b, 0x2e, 0x43, 0x68, 0x75, 0x6e, 0x6b, 0x22, 0x00, 0x30, 0x01, 0x12,
	0x45, 0x0a, 0x08, 0x53, 0x6e, 0x61, 0x70, 0x73, 0x68, 0x6f, 0x74, 0x12, 0x18, 0x2e, 0x6d, 0x61,
	0x63, 0x68, 0x69, 0x6e, 0x61, 0x2e, 0x53, 0x6e, 0x61, 0x70, 0x73, 0x68, 0x6f, 0x74, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x19, 0x2e, 0x6d, 0x61, 0x63, 0x68, 0x69, 0x6e, 0x61, 0x2e,
	0x53, 0x6e, 0x61, 0x70, 0x73, 0x68, 0x6f, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x22, 0x00, 0x28, 0x01, 0x30, 0x01, 0x12, 0x3f, 0x0a, 0x06, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x73,
	0x12, 0x16, 0x2e, 0x6d, 0x61, 0x63, 0x68, 0x69, 0x6e, 0x61, 0x2e, 0x45, 0x76, 0x65, 0x6e, 0x74,
	0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x17, 0x2e, 0x6d, 0x61, 0x63, 0x68, 0x69,
	0x6e, 0x61, 0x2e, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x22, 0x00, 0x28, 0x01, 0x30, 0x01, 0x12, 0x4c, 0x0a, 0x0b, 0x4d, 0x61, 0x63, 0x68, 0x69,
	0x6e, 0x61, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x1b, 0x2e, 0x6d, 0x61, 0x63, 0x68, 0x69, 0x6e, 0x61,
	0x2e, 0x4d, 0x61, 0x63, 0x68, 0x69, 0x6e, 0x61, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x1c, 0x2e, 0x6d, 0x61, 0x63, 0x68, 0x69, 0x6e, 0x61, 0x2e, 0x4d, 0x61,
	0x63, 0x68, 0x69, 0x6e, 0x61, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x22, 0x00, 0x30, 0x01, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_machina_proto_rawDescOnce sync.Once
	file_machina_proto_rawDescData = file_machina_proto_rawDesc
)

func file_machina_proto_rawDescGZIP() []byte {
	file_machina_proto_rawDescOnce.Do(func() {
		file_machina_proto_rawDescData = protoimpl.X.CompressGZIP(file_machina_proto_rawDescData)
	})
	return file_machina_proto_rawDescData
}

var file_machina_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_machina_proto_msgTypes = make([]protoimpl.MessageInfo, 23)
var file_machina_proto_goTypes = []interface{}{
	(ArrowIpcMessage_Kind)(0),                  // 0: machina.ArrowIpcMessage.Kind
	(*WatchProcessesRequest)(nil),              // 1: machina.WatchProcessesRequest
	(*Update)(nil),                             // 2: machina.Update
	(*GetExecutableRequest)(nil),               // 3: machina.GetExecutableRequest
	(*SnapshotRequest)(nil),                    // 4: machina.SnapshotRequest
	(*EventsRequest)(nil),                      // 5: machina.EventsRequest
	(*ArrowEncodedData)(nil),                   // 6: machina.ArrowEncodedData
	(*ArrowIpcMessage)(nil),                    // 7: machina.ArrowIpcMessage
	(*ArrowIpcStream)(nil),                     // 8: machina.ArrowIpcStream
	(*ArrowIpcStreams)(nil),                    // 9: machina.ArrowIpcStreams
	(*EventsResponse)(nil),                     // 10: machina.EventsResponse
	(*SnapshotResponse)(nil),                   // 11: machina.SnapshotResponse
	(*MachinaInfoRequest)(nil),                 // 12: machina.MachinaInfoRequest
	(*MachinaInfoResponse)(nil),                // 13: machina.MachinaInfoResponse
	(*SnapshotRequest_Setup)(nil),              // 14: machina.SnapshotRequest.Setup
	(*SnapshotRequest_Snapshot)(nil),           // 15: machina.SnapshotRequest.Snapshot
	(*EventsRequest_Setup)(nil),                // 16: machina.EventsRequest.Setup
	(*EventsRequest_Stream)(nil),               // 17: machina.EventsRequest.Stream
	(*EventsRequest_Finish)(nil),               // 18: machina.EventsRequest.Finish
	(*EventsResponse_Event)(nil),               // 19: machina.EventsResponse.Event
	(*EventsResponse_ApproximateBootTime)(nil), // 20: machina.EventsResponse.ApproximateBootTime
	(*EventsResponse_Attached)(nil),            // 21: machina.EventsResponse.Attached
	(*EventsResponse_SummaryStatistics)(nil),   // 22: machina.EventsResponse.SummaryStatistics
	(*EventsResponse_Detached)(nil),            // 23: machina.EventsResponse.Detached
	(*LabelRule)(nil),                          // 24: process.LabelRule
	(*Process)(nil),                            // 25: process.Process
	(*timestamppb.Timestamp)(nil),              // 26: google.protobuf.Timestamp
	(*chunkpb.Chunk)(nil),                      // 27: chunk.Chunk
}
var file_machina_proto_depIdxs = []int32{
	24, // 0: machina.WatchProcessesRequest.label_rules:type_name -> process.LabelRule
	25, // 1: machina.Update.added:type_name -> process.Process
	14, // 2: machina.SnapshotRequest.setup:type_name -> machina.SnapshotRequest.Setup
	15, // 3: machina.SnapshotRequest.snapshot:type_name -> machina.SnapshotRequest.Snapshot
	16, // 4: machina.EventsRequest.setup:type_name -> machina.EventsRequest.Setup
	17, // 5: machina.EventsRequest.stream:type_name -> machina.EventsRequest.Stream
	18, // 6: machina.EventsRequest.finish:type_name -> machina.EventsRequest.Finish
	0,  // 7: machina.ArrowIpcMessage.kind:type_name -> machina.ArrowIpcMessage.Kind
	6,  // 8: machina.ArrowIpcMessage.encoded_data:type_name -> machina.ArrowEncodedData
	7,  // 9: machina.ArrowIpcStream.messages:type_name -> machina.ArrowIpcMessage
	8,  // 10: machina.ArrowIpcStreams.streams:type_name -> machina.ArrowIpcStream
	19, // 11: machina.EventsResponse.event:type_name -> machina.EventsResponse.Event
	20, // 12: machina.EventsResponse.approximate_boot_time:type_name -> machina.EventsResponse.ApproximateBootTime
	21, // 13: machina.EventsResponse.attached:type_name -> machina.EventsResponse.Attached
	23, // 14: machina.EventsResponse.detached:type_name -> machina.EventsResponse.Detached
	9,  // 15: machina.EventsResponse.arrow_streams:type_name -> machina.ArrowIpcStreams
	26, // 16: machina.SnapshotResponse.timestamp:type_name -> google.protobuf.Timestamp
	26, // 17: machina.SnapshotResponse.approximate_boot_time:type_name -> google.protobuf.Timestamp
	22, // 18: machina.EventsResponse.Detached.summary_statistics:type_name -> machina.EventsResponse.SummaryStatistics
	1,  // 19: machina.Machina.WatchProcesses:input_type -> machina.WatchProcessesRequest
	3,  // 20: machina.Machina.GetExecutable:input_type -> machina.GetExecutableRequest
	4,  // 21: machina.Machina.Snapshot:input_type -> machina.SnapshotRequest
	5,  // 22: machina.Machina.Events:input_type -> machina.EventsRequest
	12, // 23: machina.Machina.MachinaInfo:input_type -> machina.MachinaInfoRequest
	2,  // 24: machina.Machina.WatchProcesses:output_type -> machina.Update
	27, // 25: machina.Machina.GetExecutable:output_type -> chunk.Chunk
	11, // 26: machina.Machina.Snapshot:output_type -> machina.SnapshotResponse
	10, // 27: machina.Machina.Events:output_type -> machina.EventsResponse
	13, // 28: machina.Machina.MachinaInfo:output_type -> machina.MachinaInfoResponse
	24, // [24:29] is the sub-list for method output_type
	19, // [19:24] is the sub-list for method input_type
	19, // [19:19] is the sub-list for extension type_name
	19, // [19:19] is the sub-list for extension extendee
	0,  // [0:19] is the sub-list for field type_name
}

func init() { file_machina_proto_init() }
func file_machina_proto_init() {
	if File_machina_proto != nil {
		return
	}
	file_process_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_machina_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WatchProcessesRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_machina_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Update); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_machina_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetExecutableRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_machina_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SnapshotRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_machina_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EventsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_machina_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ArrowEncodedData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_machina_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ArrowIpcMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_machina_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ArrowIpcStream); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_machina_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ArrowIpcStreams); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_machina_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EventsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_machina_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SnapshotResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_machina_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MachinaInfoRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_machina_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MachinaInfoResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_machina_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SnapshotRequest_Setup); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_machina_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SnapshotRequest_Snapshot); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_machina_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EventsRequest_Setup); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_machina_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EventsRequest_Stream); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_machina_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EventsRequest_Finish); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_machina_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EventsResponse_Event); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_machina_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EventsResponse_ApproximateBootTime); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_machina_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EventsResponse_Attached); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_machina_proto_msgTypes[21].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EventsResponse_SummaryStatistics); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_machina_proto_msgTypes[22].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EventsResponse_Detached); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_machina_proto_msgTypes[3].OneofWrappers = []interface{}{
		(*SnapshotRequest_Setup_)(nil),
		(*SnapshotRequest_Snapshot_)(nil),
	}
	file_machina_proto_msgTypes[4].OneofWrappers = []interface{}{
		(*EventsRequest_Setup_)(nil),
		(*EventsRequest_Stream_)(nil),
		(*EventsRequest_Finish_)(nil),
	}
	file_machina_proto_msgTypes[9].OneofWrappers = []interface{}{
		(*EventsResponse_Event_)(nil),
		(*EventsResponse_ApproximateBootTime_)(nil),
		(*EventsResponse_Attached_)(nil),
		(*EventsResponse_Detached_)(nil),
		(*EventsResponse_ArrowStreams)(nil),
	}
	file_machina_proto_msgTypes[16].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_machina_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   23,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_machina_proto_goTypes,
		DependencyIndexes: file_machina_proto_depIdxs,
		EnumInfos:         file_machina_proto_enumTypes,
		MessageInfos:      file_machina_proto_msgTypes,
	}.Build()
	File_machina_proto = out.File
	file_machina_proto_rawDesc = nil
	file_machina_proto_goTypes = nil
	file_machina_proto_depIdxs = nil
}
