// Code generated by "stringer -type=OpCode"; DO NOT EDIT.

package stackmachine

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[OpCodeInvalid-0]
	_ = x[OpCodeCall-1]
	_ = x[OpCodeCondJump-2]
	_ = x[OpCodeDecrement-3]
	_ = x[OpCodeEnqueueEmptyInterface-4]
	_ = x[OpCodeEnqueueInterface-5]
	_ = x[OpCodeEnqueuePointer-6]
	_ = x[OpCodeEnqueueSliceHeader-7]
	_ = x[OpCodeEnqueueStringHeader-8]
	_ = x[OpCodeEnqueueMapHeader-9]
	_ = x[OpCodeJump-10]
	_ = x[OpCodePop-11]
	_ = x[OpCodePushImm-12]
	_ = x[OpCodePushOffset-13]
	_ = x[OpCodePushSliceLen-14]
	_ = x[OpCodeReturn-15]
	_ = x[OpCodeSetOffset-16]
	_ = x[OpCodeShiftOffset-17]
	_ = x[OpCodeEnqueueBiasedPointer-18]
	_ = x[OpCodeDereferenceCFAOffset-19]
	_ = x[OpCodeCopyFromRegister-20]
	_ = x[OpCodeZeroFill-21]
	_ = x[OpCodePrepareFrameData-22]
}

const _OpCode_name = "OpCodeInvalidOpCodeCallOpCodeCondJumpOpCodeDecrementOpCodeEnqueueEmptyInterfaceOpCodeEnqueueInterfaceOpCodeEnqueuePointerOpCodeEnqueueSliceHeaderOpCodeEnqueueStringHeaderOpCodeEnqueueMapHeaderOpCodeJumpOpCodePopOpCodePushImmOpCodePushOffsetOpCodePushSliceLenOpCodeReturnOpCodeSetOffsetOpCodeShiftOffsetOpCodeEnqueueBiasedPointerOpCodeDereferenceCFAOffsetOpCodeCopyFromRegisterOpCodeZeroFillOpCodePrepareFrameData"

var _OpCode_index = [...]uint16{0, 13, 23, 37, 52, 79, 101, 121, 145, 170, 192, 202, 211, 224, 240, 258, 270, 285, 302, 328, 354, 376, 390, 412}

func (i OpCode) String() string {
	if i >= OpCode(len(_OpCode_index)-1) {
		return "OpCode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _OpCode_name[_OpCode_index[i]:_OpCode_index[i+1]]
}
