// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package apipb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ApiServiceClient is the client API for ApiService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ApiServiceClient interface {
	// CaptureSnapshot captures a snapshot of the specified environment or the
	// specified process. If no snapshots are snapshotted successfully, it returns
	// an error containing SnapshotError as a detail. If at least one process
	// snapshot is successful, the RPC is successful.
	CaptureSnapshot(ctx context.Context, in *CaptureSnapshotRequest, opts ...grpc.CallOption) (*CaptureSnapshotResponse, error)
	// DeleteRecording deletes the recording with the specified id.
	DeleteRecording(ctx context.Context, in *DeleteRecordingRequest, opts ...grpc.CallOption) (*DeleteRecordingResponse, error)
}

type apiServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewApiServiceClient(cc grpc.ClientConnInterface) ApiServiceClient {
	return &apiServiceClient{cc}
}

func (c *apiServiceClient) CaptureSnapshot(ctx context.Context, in *CaptureSnapshotRequest, opts ...grpc.CallOption) (*CaptureSnapshotResponse, error) {
	out := new(CaptureSnapshotResponse)
	err := c.cc.Invoke(ctx, "/api.ApiService/CaptureSnapshot", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiServiceClient) DeleteRecording(ctx context.Context, in *DeleteRecordingRequest, opts ...grpc.CallOption) (*DeleteRecordingResponse, error) {
	out := new(DeleteRecordingResponse)
	err := c.cc.Invoke(ctx, "/api.ApiService/DeleteRecording", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ApiServiceServer is the server API for ApiService service.
// All implementations must embed UnimplementedApiServiceServer
// for forward compatibility
type ApiServiceServer interface {
	// CaptureSnapshot captures a snapshot of the specified environment or the
	// specified process. If no snapshots are snapshotted successfully, it returns
	// an error containing SnapshotError as a detail. If at least one process
	// snapshot is successful, the RPC is successful.
	CaptureSnapshot(context.Context, *CaptureSnapshotRequest) (*CaptureSnapshotResponse, error)
	// DeleteRecording deletes the recording with the specified id.
	DeleteRecording(context.Context, *DeleteRecordingRequest) (*DeleteRecordingResponse, error)
	mustEmbedUnimplementedApiServiceServer()
}

// UnimplementedApiServiceServer must be embedded to have forward compatible implementations.
type UnimplementedApiServiceServer struct {
}

func (UnimplementedApiServiceServer) CaptureSnapshot(context.Context, *CaptureSnapshotRequest) (*CaptureSnapshotResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CaptureSnapshot not implemented")
}
func (UnimplementedApiServiceServer) DeleteRecording(context.Context, *DeleteRecordingRequest) (*DeleteRecordingResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteRecording not implemented")
}
func (UnimplementedApiServiceServer) mustEmbedUnimplementedApiServiceServer() {}

// UnsafeApiServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ApiServiceServer will
// result in compilation errors.
type UnsafeApiServiceServer interface {
	mustEmbedUnimplementedApiServiceServer()
}

func RegisterApiServiceServer(s grpc.ServiceRegistrar, srv ApiServiceServer) {
	s.RegisterService(&ApiService_ServiceDesc, srv)
}

func _ApiService_CaptureSnapshot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CaptureSnapshotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiServiceServer).CaptureSnapshot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.ApiService/CaptureSnapshot",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiServiceServer).CaptureSnapshot(ctx, req.(*CaptureSnapshotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ApiService_DeleteRecording_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteRecordingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiServiceServer).DeleteRecording(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.ApiService/DeleteRecording",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiServiceServer).DeleteRecording(ctx, req.(*DeleteRecordingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ApiService_ServiceDesc is the grpc.ServiceDesc for ApiService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ApiService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.ApiService",
	HandlerType: (*ApiServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CaptureSnapshot",
			Handler:    _ApiService_CaptureSnapshot_Handler,
		},
		{
			MethodName: "DeleteRecording",
			Handler:    _ApiService_DeleteRecording_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api.proto",
}
